### ISSUE TITLE
lodash require

### ISSUE THREAD

**Issue by montogeek** [survivejs/webpack-merge#1]
Hi!

It is possible to just require the `lodash` functions that this package actually needs?

Thanks!

**Comment by bebraw** [comment]
Can you provide more information? I'm missing the context.

**Comment by montogeek** [comment]
This package only use 3 functions from `lodash`, but it's important the whole package.
Well, I think that is not possible because `lodash` does not publish a package for every set of functions.

**Comment by montogeek** [comment]
Hey!

I just found https://www.npmjs.com/browse/keyword/lodash-modularized, I was so wrong, we can require only those 3 packages:
https://www.npmjs.com/package/lodash.isarray
https://www.npmjs.com/package/lodash.isplainobject
https://www.npmjs.com/package/lodash.merge

What you think?

**Comment by bebraw** [comment]
Sure, that sounds like a nice change. Want to PR or should I patch it?

**Comment by montogeek** [comment]
I will PR :)
