### ISSUE TITLE
Merging unique CopyWebpackPlugin

### ISSUE THREAD

**Issue by ctaylo21** [survivejs/webpack-merge#103]
Hello,
 I started with [this example](https://github.com/survivejs/webpack-merge#mergeuniquefield-fields-field--field) and I've been struggling trying to figure out how to merge a unique version of `CopyWebpackPlugin`.

[Another issue](https://github.com/survivejs/webpack-merge/issues/56) brought this up, but calling `new CopyWebpackPlugin()` returns `{ apply: [Function: apply] }` and I can't get `merge.unique` to properly set the unique value from the 2nd config. I'm not sure if this is user error or if it's not feasible. With some tweaking of the "getter" function, it appears I can get `webpack-merge` to set a single unique value, but it always uses seems to use first instance of `CopyWebpackPlugin`.

Example code:

```
const merge = require('webpack-merge');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const path = require('path');
const prod = require('./prod.js');
const dev = require('./dev.js');

module.exports = merge({
  customizeArray: merge.unique(
    'plugins',
    ['apply'],
    plugin => plugin.hasOwnProperty('apply') && 'apply'
  ),
})(prod, {
  plugins: [
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static/html/*.html'),
        to: path.resolve(__dirname, '../build'),
        flatten: true,
      },
      {
        from: path.resolve(__dirname, '../static/html/local/*.html'),
        to: path.resolve(__dirname, '../build'),
        flatten: true,
      },
    ]),
  ],
});
```

As for the why the `CopyWebpackPlugin` is unique, It seems like it's possibly related to https://github.com/webpack-contrib/copy-webpack-plugin/issues/268 since the plugins array looks something like this for my webpack config:

```
[ CleanWebpackPlugin {... },
  LimitChunkCountPlugin {...},
  { apply: [Function: apply] }, // CopyWebpackPlugin is different here
  MiniCssExtractPluginCleanup {},
  MiniCssExtractPlugin {...},
  LodashModuleReplacementPlugin {...}
]
....
```

I think I am just trying to use `merge.unique` incorrectly and my example above will just remove the 2nd config's `CopyWebpackPlugin` entry. Any recommended approach for doing this given that `CopyWebpackPlugin` seems to be a special case?

**Comment by bebraw** [comment]
To keep things simple (and less complicated), I would consider doing a `copy` helper and then applying that per target.

Can you set up a small repo? I can do a basic setup there based on what you have so far.

Sorry for the late reply. Super busy lately.

**Comment by ctaylo21** [comment]
No worries about the delay, I majorly appreciate the project and all the work you put in. I will try to find some time today to set up a repo to recreate the issue. 

We ended up finding better ways to combine/merge our webpack configs so we now just have a single place that uses the `CopyWebpackPlugin` and relies on environment variables to determine which path to load.

That being said, someone else may run into the issue so having a solution would be nice for the future. I'll let you know when I can get a small repo set up.

**Comment by DBosley** [comment]
IDK if this will help anyone else, but I just spent an hour trying to understand how merge.unique works, and I finally get it.

The signature he lists is this:
`merge.unique(<field>, <fields>, field => field)`
- The first <field> is the config property to look through for duplicates (in the documentation example, 'plugins')
- <fields> represents the values that should be unique when you run the field=>field function on each duplicate

So for the documented example, he's saying that there should be only one plugin that has `plugin.constructor.name` matching `HotModuleReplacementPlugin`. `merge.unique` will keep the first one it sees in the array, and discard all others.

**Comment by mihaisavezi** [comment]
> IDK if this will help anyone else, but I just spent an hour trying to understand how merge.unique works, and I finally get it.
> 
> The signature he lists is this:
> `merge.unique(<field>, <fields>, field => field)`
> 
> * The first `<field>` is the config property to look through for duplicates (in the documentation example, 'plugins')
> * `<fields>` represents the values that should be unique when you run the `field=>field` function on each duplicate
> 
> So for the documented example, he's saying that there should be only one plugin that has `plugin.constructor.name` matching `HotModuleReplacementPlugin`. `merge.unique` will keep the first one it sees in the array, and discard all others.

this should go in the readme

**Comment by Guneetgstar** [comment]
I came here to clear how it works but this made me more confused as the [documentation](https://github.com/survivejs/webpack-merge) says:
```
Output contains only single HotModuleReplacementPlugin now and it's going to be the last plugin instance.
```
And you are saying:

> `merge.unique` will keep the first one it sees in the array, and discard all others.

**Comment by bebraw** [comment]
@Guneetgstar I've reworked the logic since this issue was opened. See the current implementation here: https://github.com/survivejs/webpack-merge/blob/master/src/unique.ts . The related test at https://github.com/survivejs/webpack-merge/blob/master/test/unique.test.ts .

Do you have a use case where you have to alter the order? Now it's picking up the last one but I can expose the logic so that you can swap the order. If you need this, please open an issue and I'll expose the logic.

**Comment by Guneetgstar** [comment]
@bebraw Picking up the last one? I just ended up implementing this to my `webpack` to pick the first `EnvironmentPlugin` in `webpack.dev.config.js` and `webpack.base.config.js`. The logic is to pick from the base config-if, not in any other extended config which is working fine for me. I am declaring env variable based on profiles in `webpack`. I guess I am getting it wrong but the current implementation (which I have implemented) seems more reasonable.
And as you asked it, I would add that it's up to the use case, the best thing you can do is add an optional `boolean` parameter with `unique` to customize which one to pick, first or last (although this is also not something that would be a great feature request as one can get this behaviour switching the positions manually).

**Comment by bebraw** [comment]
In the current code, the last encountered match wins, correct.

**Comment by Guneetgstar** [comment]
Ok, I just confirmed it and as per my current configuration both the approaches (first/last) work fine hence I didn't get to see the diff as I am concating them at the end anyways(found/not found).
```
plugins: options.plugins.concat([
    new webpack.EnvironmentPlugin({
      NODE_ENV: 'development',
    }),
  ])
```
