### ISSUE TITLE
Multiple merging has TypeScript error

### ISSUE THREAD

**Issue by tysonmatanich** [survivejs/webpack-merge#112]
The example (https://github.com/survivejs/webpack-merge#multiple-merging) for multiple merging gives the following TypeScript error:

```Type '{ server: { target: string; output: { path: string; filename: string; }; }; client: { output: { path: string; filename: string; }; }; }' has no properties in common with type 'Configuration'.```

The `Configuration` interface imported from webpack (@types/webpack) doesn't allow for server/client object keys. Something like the following could allow for this:

```ts
interface ConfigurationMap {
  [name: string]: Configuration;
}
```

**Comment by logusgraphics** [comment]
Same as #110

**Comment by uinz** [comment]
I create a [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34736/files)

**Comment by chinesedfan** [comment]
@uinz's PR has been merged, so it should be fixed, as well as #110.

**Comment by rpivo** [comment]
Does anyone have any more info on this other than #110 and #112? I've been troubleshooting typing issues using webpack-dev-server with webpack-merge.

**Comment by TheGrimSilence** [comment]
`merge({...},frontend as webpack.Configuration)` works just fine, except I can't use conditional plugins or it fails.

**Comment by bebraw** [comment]
This will get fixed in v5 (ported to TS).

**Comment by chinesedfan** [comment]
@bebraw Hi, what's the progress of v5 and how can I help?

**Comment by bebraw** [comment]
Hi,

I have the work at develop branch in case you want to check the status and try it out. I think I will break the basic merge function in two next to get proper return types instead of any.
