### ISSUE TITLE
merge.smart: Loaders must match both include and exclude, missing in documentation.

### ISSUE THREAD

**Issue by denysonique** [survivejs/webpack-merge#113]
Documentation currently suggests that only test needs to much, I was confused initially getting duplicate entries. For `merge.smart()` both `test` and `exclude` must match and perhaps `include`?

**Comment by bebraw** [comment]
@denysonique Can you send me a doc PR? Thanks.

**Comment by chinesedfan** [comment]
@bebraw Mentioned `enforce` as well in #122.
