### ISSUE TITLE
how to disable AMD loader

### ISSUE THREAD

**Issue by muraliwise** [survivejs/webpack-merge#114]
module: {
  rules: [
    {
      parser: {
        amd: false
      }
    }
  ]
}

using chainWebpack in vue.config js file

**Comment by bebraw** [comment]
Could you link to a repository? It's hard to say otherwise. I think you should be able to override the default setting.

**Comment by muraliwise** [comment]
We need to link the npm modules to project that time we are over writing in webpack config

module: {
rules: [
{
parser: {
amd: false
}
}
]
}

like 

But

vue.config how to do this one?

**Comment by bebraw** [comment]
Hi,

I don't develop Vue myself. Could you ask in the Vue community for more guidance? I don't know how they manage configuration over there.

**Comment by bebraw** [comment]
There's not enough information to debug so I'll close this one.
