### ISSUE TITLE
Please briefly mention at top of Readme whether it merges right to left or left to right.

### ISSUE THREAD

**Issue by codekiln** [survivejs/webpack-merge#115]
Please include a comment in the readme intro indicating whether it merges arguments from right to left or from left to right. It is not currently obvious which object will "win" if they have the same keys.

**Comment by bebraw** [comment]
Hi,

Can you give a small example of what you have in mind? I'll add something based on that.

**Comment by codekiln** [comment]
I'm picturing something like this: 

```
// Please note that where keys match, the objects to the right take precedence 
var output = merge({fruit: "apple", color: "red"}, {fruit: "strawberries"});
console.log(output);
// { color: "red", fruit: "strawberries"}
```
