### ISSUE TITLE
merge multiple common configs with production/dev config?

### ISSUE THREAD

**Issue by nitwhiz** [survivejs/webpack-merge#118]
I try to merge an array of webpack configs, with different output definitions with *an* more specific config.
What I'm trying to achieve is
```
merge([configA, configB, configC], configD)
-> [configAMergedWithconfigD, configBMergedWithconfigD, configCMergedWithconfigD]
```

Any hints on how to achieve this easily?

**Comment by bebraw** [comment]
Hi,

I would do something like this:

```javascript
const configs = [configA, configB, configC];
const commonConfig = configD;

const mergedConfigs = configs.map(config => merge(commonConfig, config));
```

I hope this helps. Likely you can refactor from here to your tastes.

**Comment by bebraw** [comment]
Hi,

Did you solve this problem? It sounds like a bit of programming on top of
merge?

**Comment by nitwhiz** [comment]
I solved it a good 2 months ago, yeah, but I don't know my actual use case anymore to be honest.

All I remember is, that your suggestion was enough to get me through it. In the end I had do this completely differently anyway, I was heavily over engineering there..^^
