### ISSUE TITLE
Check issuer in smart merging

### ISSUE THREAD

**Issue by kirilldronkin** [survivejs/webpack-merge#124]
Consider the next merging:

```js
merge.smart({
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          'css-loader',
          'postcss-loader'
        ]
      }
    ]
  }
}, {
  module: {
    rules: [
      {
        test: /\.css$/,
        issuer: /\.html$/,
        use: [
          'file-loader'
        ]
      },
      {
        test: /\.css$/,
        use: [
          'style-loader',
          'css-loader',
          'postcss-loader'
        ]
       }
    ]
  }
});
```

In the current implementation the final config will include 1 rule entry with 4 merged loaders, instead of 2 separate entries.

**Comment by bebraw** [comment]
I'll drop support for `merge.smart` in the next major version as it's tricky to support due to webpack configuration complexity and all the corner cases.

Can you find a way to port above to a regular `merge` or `merge.strategy`?
