### ISSUE TITLE
[Bug] oneOf merge wrong

### ISSUE THREAD

**Issue by eightHundreds** [survivejs/webpack-merge#128]
1. Check the version of **webpack-merge** you are using. If it's not the newest version, update and try again (see changelog while updating!).
2. If the issue is still there, write a minimal script showing the problem and expected output. You can also set up a repository (even better).
3. Include the script to the issue. Mention Node version and OS in your report.

version 4.2.2

``` js
const { stringify } = require('javascript-stringify')
const smartMerge = require('webpack-merge').smart

describe.only('merge test', () => {
  test('merge', () => {
    const a = {
      rules: [
        {
          test: /\.js$/,
          oneOf: [
            {
              resourceQuery: /inline/, // foo.css?inline
              use: 'url-loader',
            },
            {
              resourceQuery: /external/, // foo.css?external
              use: 'file-loader',
            },
          ],
        },
      ],
    }
    const expectResult = stringify(a)
    expect(stringify(smartMerge(a, a))).toBe(expectResult)
  })
})
```

![image](https://user-images.githubusercontent.com/18695431/81663533-59fa1b80-9471-11ea-88d1-255337a76700.png)

**Comment by bebraw** [comment]
It seems to work if you use `loader` instead of `use` but I know that's not ideal.

Likely I'll drop the support for `merge.smart` as it's difficult to support and it has surprising corner cases like this.
