### ISSUE TITLE
Lodash dependency causes prototype pollution issue: can you use another package instead of lodash?

### ISSUE THREAD

**Issue by marcoippolito** [survivejs/webpack-merge#134]
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @vue/cli-service                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @vue/cli-service > webpack-merge > lodash                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1523      

https://www.npmjs.com/advisories/1523 :  "No fix is currently available. Consider using an alternative package until a fix is made available."

webpack-merge@4.2.2 

Can you use another package instead of lodash?

**Comment by bebraw** [comment]
What would be a good alternative? I can resolve this in the next major version.

**Comment by marcoippolito** [comment]
@bebraw I'm not that expert of Lodash.
Just looking around I found these info:

- https://stackshare.io/lodash/alternatives

- https://js.libhunt.com/lodash-alternatives

- https://www.sitepoint.com/lodash-features-replace-es6/

**Comment by bebraw** [comment]
No worries. It’s only a couple of functions we are using so likely it’s not a big deal to replace them.

**Comment by marcoippolito** [comment]
@bebraw  Thank you very much!!!

**Comment by bebraw** [comment]
I've done this at the `develop` branch and the change is going to be included to the next major version.

**Comment by marcoippolito** [comment]
> I've done this at the `develop` branch and the change is going to be included to the next major version.

Thank you very much!!!

**Comment by bebraw** [comment]
@marcoippolito Check #136 for the beta.
