### ISSUE TITLE
[Documentation] How to use 5.x with Webpack config file?

### ISSUE THREAD

**Issue by moderndeveloperllc** [survivejs/webpack-merge#137]
I think it might be good to include information on how to use ES6 module imports (`import {merge} from 'webpack-merge';`) in a `webpack.config.js` file. Just trying to replace the old CommonJS `require()` doesn't work. From what I can see, you have to route the config file through Bable to change over the imports back to CommonJS.

Am I missing something here?

**Comment by bebraw** [comment]
Available import types depend a lot on the environment. If you do **webpack.config.babel.js**, I recall it should try to use Babel. With **webpack.config.ts**, it would go through tsc.

I think I'll rewrite the imports to CommonJS style as that's the lowest common denominator. Thanks!

**Comment by bebraw** [comment]
Included in 5.0.4.

**Comment by moderndeveloperllc** [comment]
@bebraw Thanks. I think it will cut down on the confusion with those of us who are relative Webpack/node neophytes.

**Comment by bebraw** [comment]
Yup, agreed. Thanks for bringing this up. :)
