### ISSUE TITLE
Having issues while updating from 4.2.2 to 5.1.4

### ISSUE THREAD

**Issue by ioanungurean** [survivejs/webpack-merge#148]
Hi, as I did not see an upgrade guide I willl post it here. I was using the `smartStartegy` before and I tried to use the new API but for some reason the merge is not happening as before.

```
  return merge.smartStrategy({
    "module.rules.use": "prepend"
  })
```

Is the code below equivalent to the one above? What am I doing wrong?

```
  return mergeWithCustomize({
    customizeArray: customizeArray({
      "module.rules.use.*": "prepend",
    }),
  })
```

Here is a [link to the repo](https://github.com/ioanungurean/forge-react-app/blob/master/templates/ECMAScript/devtools/webpack.config.js#L14) if that helps. 

Thank you in advance for looking over my issue. And I appologise if this is not the right place to post this issue.

**Comment by bebraw** [comment]
Hi,

Can you send me a simple example (two minimal configurations + output after merge) to help developing this feature? Is the idea to match based on `test` and then merge at `use`? Given this is specific logic, it doesn't fit the current syntax.

I've been exploring a light solution related to this at [issue 146](https://github.com/survivejs/webpack-merge/issues/146#issuecomment-690544337). The use case is far more complex there but it's possible what you have here would fit into the problem.

**Comment by bebraw** [comment]
@ioanungurean I added a new API called [mergeWithRules](https://github.com/survivejs/webpack-merge#mergewithrules). Can you check if it would work for your use case?

**Comment by ioiooi** [comment]
Having the same problem. `mergeWithRules` didn't help.

Going to stay at v 4.2.2.
[link to repo](https://github.com/ioiooi/react-starter/blob/master/webpack.prod.js)

**Comment by bebraw** [comment]
Can you open a separate issue with your current setup? Ideally it should be simplified as much as possible and something I can run.

**Comment by bebraw** [comment]
@ioiooi Ah, nevermind. Just saw your link a second too late. I'll check how it would work with v5.

**Comment by bebraw** [comment]
@ioiooi If you want to use v5, it looks like the following is a good option in your case:

```js
const common = require('./webpack.common.js');
const { mergeWithCustomize, customizeArray } = require('webpack-merge');
const webpack = require('webpack');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = mergeWithCustomize({
  customizeArray: customizeArray({
    'module.rules': 'prepend'
  }),
})(common, {...})
```

I noticed `mergeWithRules` won't work due to mini-css-extract-plugin for this case.

**Comment by ioiooi** [comment]
@bebraw sorry, for not isolating the issue and making your work harder.

Your suggested changes are working! Thank you! 👍

**Comment by bebraw** [comment]
@ioiooi No worries, it was easy enough to work against your repository. Have a nice week. 👍

**Comment by bebraw** [comment]
I'm closing this one. Feel free to open a new issue if the new API doesn't work for your use case.
