### ISSUE TITLE
How to merge webpack alias?

### ISSUE THREAD

**Issue by Aslam97** [survivejs/webpack-merge#156]
I've webpack config in `webpack.config.js` with existing aliases. and from another file I want to merge the alias from existing webpack.config.js

**webpack.config.js**

```js
module.exports = {
    resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      '@': path.join(__dirname, './resources/js'),
      '~': path.join(__dirname, './resources/sass'),
      '@assets': path.join(__dirname, './resources/assets'),
      '@govo': path.join(__dirname, './resources/js/govo'),
    },
  },
}
```
**other.js**

```js
const webpackConfig = require('./webpack.config');
const { merge } = require('webpack-merge');

const newAliases = {
  resolve: {
    alias: {
      '@layouts': path.join(__dirname, './resources/js/layouts'),
      '@components': path.join(
        __dirname,
        './resources/js/components'
      ),
    },
  },
};

const newWebpackConfig = merge(webpackConfig, newAliases);
```
`newWebpackConfig` give me the result that I want. but when running `npm` it give me error like this:

```
TypeError: Cannot read property 'startsWith' of undefined
    at isRelative (/var/www/html/my-project/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:5:17)
    at /var/www/html/my-project/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:64:15
    at Array.map (<anonymous>)
    at groupModules (/var/www/html/my-project/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:62:43)
    at formatErrors (/var/www/html/my-project/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:74:18)
    at format (/var/www/html/my-project/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:87:10)
    at format (/var/www/html/my-project/node_modules/friendly-errors-webpack-plugin/src/core/formatErrors.js:12:33)
    at Array.map (<anonymous>)
    at formatErrors (/var/www/html/my-project/node_modules/friendly-errors-webpack-plugin/src/core/formatErrors.js:15:21)
    at FriendlyErrorsWebpackPlugin.displayErrors (/var/www/html/my-project/node_modules/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:110:5)
    at doneFn (/var/www/html/my-project/node_modules/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:51:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:40:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/html/my-project/node_modules/tapable/lib/Hook.js:154:20)
    at /var/www/html/my-project/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/var/www/html/my-project/node_modules/webpack/lib/Compiler.js:499:39)
    at /var/www/html/my-project/node_modules/webpack/lib/Compiler.js:298:10
    at /var/www/html/my-project/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/html/my-project/node_modules/tapable/lib/Hook.js:154:20)
    at /var/www/html/my-project/node_modules/webpack/lib/Compiler.js:482:27
    at /var/www/html/my-project/node_modules/neo-async/async.js:2818:7
    at done (/var/www/html/my-project/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at /var/www/html/my-project/node_modules/webpack/lib/Compiler.js:464:33
    at /var/www/html/my-project/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (fs.js:156:23)
```
how can I solve this?

**Comment by bebraw** [comment]
Does it work without friendly-errors-webpack-plugin?

Which version of webpack and webpack-merge are you using?

**Comment by Aslam97** [comment]
> Does it work without friendly-errors-webpack-plugin? Which version of webpack and webpack-merge are you using?
> […](#)
> On 09.11.2020, at 04:33, Aslam ***@***.***> wrote: ﻿ I've webpack config in webpack.config.js with existing aliases. and from another file I want to merge the alias from existing webpack.config.js webpack.config.js module.exports = { resolve: { extensions: ['.js', '.vue', '.json'], alias: { '@': path.join(__dirname, './resources/js'), '~': path.join(__dirname, './resources/sass'), ***@***.***': path.join(__dirname, './resources/assets'), ***@***.***': path.join(__dirname, './resources/js/govo'), }, }, } other.js const webpackConfig = require('./webpack.config'); const { merge } = require('webpack-merge'); const newAliases = { resolve: { alias: { ***@***.***': path.join(__dirname, './resources/js/layouts'), ***@***.***': path.join( __dirname, './resources/js/components' ), }, }, }; const newWebpackConfig = merge(webpackConfig, newAliases); newWebpackConfig give me the result that I want. but when running npm it give me error like this: TypeError: Cannot read property 'startsWith' of undefined at isRelative (/var/www/html/my-project/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:5:17) at /var/www/html/my-project/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:64:15 at Array.map (<anonymous>) at groupModules (/var/www/html/my-project/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:62:43) at formatErrors (/var/www/html/my-project/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:74:18) at format (/var/www/html/my-project/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:87:10) at format (/var/www/html/my-project/node_modules/friendly-errors-webpack-plugin/src/core/formatErrors.js:12:33) at Array.map (<anonymous>) at formatErrors (/var/www/html/my-project/node_modules/friendly-errors-webpack-plugin/src/core/formatErrors.js:15:21) at FriendlyErrorsWebpackPlugin.displayErrors (/var/www/html/my-project/node_modules/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:110:5) at doneFn (/var/www/html/my-project/node_modules/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:51:14) at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:40:1) at AsyncSeriesHook.lazyCompileHook (/var/www/html/my-project/node_modules/tapable/lib/Hook.js:154:20) at /var/www/html/my-project/node_modules/webpack/lib/Compiler.js:304:22 at Compiler.emitRecords (/var/www/html/my-project/node_modules/webpack/lib/Compiler.js:499:39) at /var/www/html/my-project/node_modules/webpack/lib/Compiler.js:298:10 at /var/www/html/my-project/node_modules/webpack/lib/Compiler.js:485:14 at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1) at AsyncSeriesHook.lazyCompileHook (/var/www/html/my-project/node_modules/tapable/lib/Hook.js:154:20) at /var/www/html/my-project/node_modules/webpack/lib/Compiler.js:482:27 at /var/www/html/my-project/node_modules/neo-async/async.js:2818:7 at done (/var/www/html/my-project/node_modules/neo-async/async.js:3522:9) at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1) at /var/www/html/my-project/node_modules/webpack/lib/Compiler.js:464:33 at /var/www/html/my-project/node_modules/graceful-fs/graceful-fs.js:61:14 at FSReqCallback.oncomplete (fs.js:156:23) how can I solve this? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I'm using a laravel mix because it is pre-configured by default. for now I'm stick webpack.config.js because Idk much about webpack and friendly-error-webpack-plugin. thank for reply to my problem.
