### ISSUE TITLE
Using `mergeWithRules` with top level entries

### ISSUE THREAD

**Issue by just-jeb** [survivejs/webpack-merge#159]
I suspect it's bigger than just top level entries, most probably it also relates to anything that is a primitive.  
I'd like to merge two configs with `loaders` and `externals`.  
As per documentation in order to properly merge loaders I have to use `mergeWithRules` and indeed the loaders part works perfect.  
The problem is with `externals`, seems like it's completely ignored and used with the default strategy (`append`).
 
```ts
const a = {
  externals: ['a', 'b'],
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [{ loader: "style-loader" }, { loader: "sass-loader" }],
      },
    ],
  },
};
const b = {
  externals: ['c', 'd'],
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          {
            loader: "style-loader",
            options: {
              modules: true,
            },
          },
        ],
      },
    ],
  },
};
const result = {
  externals: ['c', 'd'],
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          {
            loader: "style-loader",
            options: {
              modules: true,
            },
          },
          { loader: "sass-loader" },
        ],
      },
    ],
  },
};

assert.deepStrictEqual(
  mergeWithRules({
    externals: 'replace'
    module: {
      rules: {
        test: "match",
        use: {
          loader: "match",
          options: "replace",
        },
      },
    },
  })(a, b),
  result
);
```

This test will fail, because `externals` are not replaced.   
Is this a bug or there is another way to merge both `loaders` and other "primitive" properties?

Node: 12.18.2
OS: macOS 10.15.6

**Comment by bebraw** [comment]
I think #151 is exactly about this problem. The problem is that `replace` doesn't do anything without a `match`.

I've prototyped a solution at https://github.com/survivejs/webpack-merge/pull/152. It would be great if you could have a quick look and let me think so I can finalize that.

**Comment by just-jeb** [comment]
Looks like it is. I commented on the PR. Overall I don't think it's the best way to go - it overcomplicates the configuration and creates confusion.  
I think the `only` should be derived from the context rather than explicitly specified.

**Comment by bebraw** [comment]
> I think the only should be derived from the context rather than explicitly specified.

Yup, it's a good way. Thanks for the feedback. I'll add some automation in the next pass. 👍
