### ISSUE TITLE
mergeUnique array customization does not work properly

### ISSUE THREAD

**Issue by trombka** [survivejs/webpack-merge#161]
Hi,

The "unique" merge array customisation works only when the second array has the same element in the same place (has the same index).

Just exchange these two lines
https://github.com/survivejs/webpack-merge/blob/develop/test/unique.test.ts#L72,L73
which should not change the result and the test will fail with a duplicated plugin.

**Comment by bebraw** [comment]
Thanks for the report. I'll try to address this in the next pass when I get to work on the plugin.
