### ISSUE TITLE
supports Node.js 10

### ISSUE THREAD

**Issue by alexander-akait** [survivejs/webpack-merge#174]
I just want to know if this is possible, we use `webpack-merge` in `webpack-cli` for commands like:
```
webpack --config one.config.js --config two.config.js --merge
```
Because webpack@5 supports Node.js@10 we supports it too in `webpack-cli`, but we can't update webpack-merge to the latest version due it require Node.js@12

**Comment by bebraw** [comment]
Do you have specific issues with Node 10?

It should be supported based on

```
  "engines": {
    "node": ">=10.0.0"
  },
```

and Travis test matrix.

**Comment by alexander-akait** [comment]
oh, I see, my mistake, I see `Breaking - Bump supported Node version to 12` in chagenlog

**Comment by alexander-akait** [comment]
Thanks

**Comment by bebraw** [comment]
Yeah, I restored Node 10 support in a later release as I realized it's important. 👍
