### ISSUE TITLE
TypeScript: use union types instead of enums

### ISSUE THREAD

**Issue by slorber** [survivejs/webpack-merge#179]
I'm using latest webpack-merge 5.*

There are a ton of reasons to not use enums in TypeScript anymore (it's not std JS), particularly if you don't even benefit from its nominal typing.

The main one I'd give in this context is that your readme examples do not work out of the box, as it requires to import the enum before being able to use it.

![image](https://user-images.githubusercontent.com/749374/113327314-1b847e00-931b-11eb-9c6c-5101afcf92e6.png)

![image](https://user-images.githubusercontent.com/749374/113327411-3656f280-931b-11eb-88f0-a5323df6c8d4.png)

**Comment by bebraw** [comment]
Can you check https://github.com/survivejs/webpack-merge/pull/185 ? To avoid breaking backwards-compatibility, I added strings as an option there so that IDEs shouldn't complain anymore.

**Comment by slorber** [comment]
thanks @bebraw , LGTM!
