### ISSUE TITLE
Figure out a neater way to compose functions (postcss)

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack-merge#18]
Loaders like [postcss-loader](https://www.npmjs.com/package/postcss-loader) define a part of their configuration through functions. You might have

```javascript
postcss: function () {
  return [precss, autoprefixer];
}
```

The problem is that it's not possible to split this up neatly yet. Ideally you should be able to have

```javascript
postcss: function () {
  return [precss];
}
```

and

```javascript
postcss: function () {
  return [autoprefixer];
}
```

The question is, how to compose this through **webpack-merge**?

**Comment by insin** [comment]
How about special-casing the merging for a top-level `postcss` property by calling the functions and appending the results - any danger from that?

I've been looking at this for nwb too, but there I can just have a default list there and tell users to pass in their own list when customising, then append them and return that from the `postcss` function.

From the last time I looked at this, am I remembering correctly that the position of autoprefixer is also significant? If you're already special-casing, it would be cool to be able to warn the user if their config looks like it will problematic.

**Comment by bebraw** [comment]
> How about special-casing the merging for a top-level postcss property by calling the functions and appending the results - any danger from that?

That feels like a merge strategy. So we would get something like

```javascript
merge.strategy({postcss: function(a, b) {
  return merge(a(), b());
}});
```

> From the last time I looked at this, am I remembering correctly that the position of autoprefixer is significant? If you're already special-casing, it would be cool to be able to warn the user if their config looks like it will problematic.

I don't know. Maybe this is one of those things that could be handled within a postcss specific merge strategy?

I've been discussing an alternative solution at https://github.com/postcss/postcss-loader/issues/69 . If we made it so that **postcss-loader** supported arrays and composition, that would make the problem disappear as we append by default. Then you would get exactly the result I described above as you would end up with

```javascript
postcss: [
  function () {
    return [precss];
  },
  function () {
    return [autoprefixer];
  }
]
```

after merge. **postcss-loader** could pick this up, apply and merge to

```javascript
postcss: function () {
  return [precss, autoprefixer];
}
```

That's easy code to write. **postcss-loader** supports also returning objects, but that can be dealt with separately. The only worrying case is the mixed one (arrays and objects), but in that case an error could be thrown and that could be disallowed entirely.

I guess the question is, what's the right place to solve this. Perhaps allowing a function based strategy is a good idea even if we end up solving it at the loader level.

**Comment by insin** [comment]
I'm back look at this for nwb - do you know why all the postcss-loader examples use the function config form?

It looks like it accepts Arrays or Objects directly and none of the examples make use of the `this` value the loader sets as context for the call, or as an argument.

What can you actually do with whatever `this` is inside a loader? :)

**Comment by bebraw** [comment]
@insin Good question. It might be worth commenting at https://github.com/postcss/postcss-loader/issues/69 . I've been a bit busy with work lately so I haven't had a lot of cycles for this.

**Comment by bebraw** [comment]
I'm closing this as postcss-loader supports array mode already. It's a little puzzling though that all the examples use the function form, though.

There's not much we can do with functions. We could do something silly like write a function that calls the merged functions in succession and concatenates the result, but that would be awfully specific.
