### ISSUE TITLE
Using Lodash utils as an alternative to `webpack-merge` ...

### ISSUE THREAD

**Issue by loicraux** [survivejs/webpack-merge#187]
Hi!

This is not a bug report or a suggestion for a new feature, but rather a post to start a discussion or debate about `webpack-merge` APIs...

In order to avoid duplication of code in my WebPack configurations (which is what everyone wants, isn't it?), I obviously got interested in `webpack-merge`.
So I took a look at its documentation, to finally realize that reading it was not enough to understand what each merge strategy was actually doing. I had to go to the `webpack-merge` source code to understand what exactly each configuration merge strategy did.

Once I have determined which merge strategy works for me, fine, I can use it, but the next person who is going to maintain these configurations is going to have to make the same effort of reading the `webpack-merge` source code to understand what is being done and what they can and cannot change.

Until I realized that by using some of the Lodash utilities, I can write DRY WebPack configurations, and configurations that everyone understands and can maintain, as long as the developer masters the Lodash primitives, which are much easier to master and grasp.

For example, given this basic configuration :
```ts
import { resolve } from 'path';
import { Configuration } from 'webpack';
import { isEmpty } from 'lodash';
import { Platform } from './scripts/packaging/platform';

export function getPlatformFromEnv(): Platform {
    // ...
}

export const baseConfig: Configuration = {
    output: {
        path: resolve(__dirname, 'app', 'dist'),
        filename: '[name].js'
    },
    node: {
        __dirname: false,
        __filename: false
    },
    resolve: {
        extensions: ['.tsx', '.ts', '.js', '.json']
    },
    devtool: 'source-map',
    plugins: []
};
```

I have this derived configuration that makes use of Lodash's `concat` and `...` spread syntax to extend the base config :

```ts
import { resolve } from 'path';
import { Configuration, DefinePlugin } from 'webpack';
import * as HtmlWebpackPlugin from 'html-webpack-plugin';
import { baseConfig } from './webpack.base.config';
import { Platform } from './scripts/packaging/platform';
import { concat } from 'lodash';

export function getRendererConfig(platform: Platform): Configuration {
    return {
        ...baseConfig, // <========= 
        target: 'electron-renderer',
        entry: {
            bundle: './app/renderer'
        },
        module: {
            rules: [
                {
                    test: /\.tsx?$/,
                    include: [resolve(__dirname, 'app')],
                    exclude: [resolve(__dirname, 'app', 'main.ts')],
                    loader: 'ts-loader'
                },
                {
                    test: /\.(?:ico|gif|png|jpg|jpeg|webp|woff|woff2|ttf|otf|eot|svg)$/,
                    type: 'asset/resource'
                }
            ]
        },
        plugins: concat(baseConfig.plugins, [  // <========= 
            new HtmlWebpackPlugin({
                filename: '../app.html',
                template: 'template.ejs',
                title: platform.htmlDocumentTitle
            }),
            new DefinePlugin({
                'process.env.APP_NAME': JSON.stringify(platform.name)
            })
        ])
    };
}
```

Eventually I have this final "grandchild" configuration making use of Lodash's `concat `and `find` 👍🏻 

```ts
import { resolve } from 'path';
import { Configuration as WebpackConfiguration, HotModuleReplacementPlugin } from 'webpack';
import { Configuration as WebpackDevServerConfiguration } from 'webpack-dev-server';
import { getPlatformFromEnv } from './webpack.base.config';
import { getRendererConfig } from './webpack.renderer.config';
import 'webpack-dev-server';
import { concat, find } from 'lodash';

let port: number = parseInt(process.env.PORT, 10);
if (isNaN(port)) {
    port = 3000;
}

// Hacking the webpack-dev-server types that are wrong
interface Configuration extends WebpackConfiguration {
    devServer?: WebpackDevServerConfiguration;
}

const rendererConfig = getRendererConfig(getPlatformFromEnv());

const config: Configuration = {
    ...rendererConfig, // <===========
    mode: 'development',
    devtool: 'inline-source-map',
    entry: ['react-hot-loader/patch', './app/renderer'],
    output: {
        ...rendererConfig.output,  // <===========
        publicPath: `http://localhost:${port}/dist/`
    },
    optimization: {
        moduleIds: 'named'
    },
    module: {
        rules: concat(find(rendererConfig.module?.rules, { type: 'asset/resource'}), [  // <===========
            {
                test: /\.tsx?$/,
                include: [resolve(__dirname, 'app')],
                exclude: [resolve(__dirname, 'app', 'main.ts')],
                use: ['react-hot-loader/webpack', 'ts-loader']
            },
            {
                test: /\.(scss|sass)$/,
                // Loaders are chained by passing multiple loaders,
                // applied from right to left (last to first configured):
                use: [
                    // Creates `style` nodes from JS strings
                    'style-loader',
                    // Translates CSS into CommonJS
                    'css-loader',
                    // Compiles Sass to CSS
                    'sass-loader'
                ]
            }
        ])
    },
    plugins: concat(rendererConfig.plugins, [  // <===========
        new HotModuleReplacementPlugin()
    ]),
    devServer: {
        port,
        compress: true,
        noInfo: true,
        stats: 'errors-only',
        inline: true,
        hot: true,
        headers: { 'Access-Control-Allow-Origin': '*' },
        historyApiFallback: true
    }
};

export default config;
```
Here, in this last config, my "problem" was to somehow overwrite the rule for tsx files by a new one... Easily solved by using Lodash's `find(rendererConfig.module?.rules, { type: 'asset/resource'})` !

I can, using Lodash and exporting the right parts of the configuration, create this derived configuration, without duplicating pieces of configurations and having readable and understandable derived configurations without a "magical" and obscure merge being performed by an external dependency...

So I removed webpack-merge from my dependencies, and I'm very happy with it.

I salute the effort behind `webpack-merge` and I can understand the developers who find it useful, but personally I find that `webpack-merge` doesn't bring me anything that Lodash (or even vanilla JavaScript) and the export of configuration parts can't... On the contrary I find it introduces obfuscation in my configurations.

I would be interested in your feedback and to know if some of you had the same impressions when using `webpack-merge`...

Also, maybe I've missed something and there are some complicated merges that `webpack-merge` can perform that cannot be done with Lodash utils

**Comment by bebraw** [comment]
For the vanilla merge, the basic behavior can be described as a recursive merge that's appending arrays. Personally I use only that in my work and the rest of the API is there due to legacy or due to user requirements. If you [check out my book](https://survivejs.com/webpack/), you can see how it all goes together in a complex use case with lots of webpack features.

It's totally fine to use lodash or other utilities to re-implement the ideas if you feel that works better for your use case. There was even a time when webpack-merge used lodash heavily underneath.

There are also many other ways to compose webpack configuration outside of webpack-merge(chaining etc.). I wrote this tiny package as I had to explain how to write webpack configuration in the book and then this particular solution made sense but it doesn't mean it's the right solution for all. It just happens to be convenient for this purpose and as mentioned it's the vanilla version that I prefer the most as it's the simplest to explain and understand.

At the moment the project is underfunded (no funding) apart from one time sponsorship from Google (thanks a lot!) but I try to do what I can on my spare time. This means I won't be able to do anything ambitious on this project due to other paying work, though, as there are bills to pay.

**Comment by bebraw** [comment]
As there isn't anything actionable here, let's close. It would be a lot of hassle to deprecate the package.
