### ISSUE TITLE
How to get in touch about a security issue?

### ISSUE THREAD

**Issue by zidingz** [survivejs/webpack-merge#189]
Hey there,

As there isn't a SECURITY.md or contact address in your repository, I am not sure how to contact you regarding a potential security issue.

Would you kindly provide an email so I can send you the details? Else, simply add a SECURITY.md file with an e-mail to your repository. GitHub recommends this as the best way to ensure security issues are responsibly disclosed.

Look forward to hearing from you, thanks!

**Comment by bebraw** [comment]
Thanks for the heads up. I set up a `SECURITY.md`.

As the project isn't funded at the moment, it's hard for me to guarantee a fast turnaround. Like with #188, I've decided to disclose the issues I cannot fix in public so hopefully someone else with time can send a fix.

**Comment by zidingz** [comment]
Thank you so much! And no worries, I'll drop you an email.
