### ISSUE TITLE
Missing dist folder in source

### ISSUE THREAD

**Issue by creativeRaspberry** [survivejs/webpack-merge#197]
In newest version you don't have index.js file.
when trying to npm run build I get:
Error: Cannot find module '[...]\node_modules\webpack-merge\dist\index.js'. Please verify that the package.json has a valid "main" entry

your package json has:
line 13: "main": "dist/index.js",

**Comment by bebraw** [comment]
Can you provide more information?

I get

```
 ~/Pr/tm/wm-demo/n/webpack-merge/dist  ls                                                                 ✔  16.14.2 Node
index.d.ts         join-arrays.d.ts   merge-with.d.ts    types.d.ts         unique.d.ts        utils.d.ts
index.js           join-arrays.js     merge-with.js      types.js           unique.js          utils.js
index.js.map       join-arrays.js.map merge-with.js.map  types.js.map       unique.js.map      utils.js.map
```

after installing.

Can you give exact commands to run?

**Comment by bebraw** [comment]
Looking at `node_modules\webpack-merge\dist\index.js'` and `dist/index.js`, I wonder if it could it be some path normalization issue.

Which versions of Node and npm are you using? Are you on Windows?
