### ISSUE TITLE
resolve alias

### ISSUE THREAD

**Issue by baesku789** [survivejs/webpack-merge#200]
1. Check the version of **webpack-merge** you are using. If it's not the newest version, update and try again (see changelog while updating!).
2. If the issue is still there, write a minimal script showing the problem and expected output. You can also set up a repository (even better).
3. Include the script to the issue. Mention Node version and OS in your report.

How to reslove alias in webpack.common.js ?
I write resolve alias in webpack.common.js, but when i run webpack-dev-server webpack couldn't resolve alias so i get error.
please let me do that

**Comment by bebraw** [comment]
Merging resolve.alias is supported.

As there's not enough information to debug, I am closing the issue.

**Comment by bebraw** [comment]
Re: potential error. Make sure you are merging to the same type (i.e. array, object, etc.) as otherwise, it won't merge.
