### ISSUE TITLE
Cant get to work with `exclude` with `merge.smart`

### ISSUE THREAD

**Issue by mshwery** [survivejs/webpack-merge#21]
Test case:

```js
merge.smart({
  module: {
    loaders: [
      {
        test: /\.js$/, 
        exclude: /node_modules/,
        loaders: ['babel']
      }
    ]
  }
}, { 
  module: { 
    loaders: [
      {
        test: /\.js$/, 
        exclude: /node_modules/,
        loaders: ['coffee', 'thing']
      }
    ]
  }
});
```

`module.loaders` = 
```js
[
  {
    test: /\.js$/,
    exclude: /node_modules/,
    loaders: [ 'coffee', 'thing' ]
  },
  {
    test: /\.js$/,
    exclude: /node_modules/,
    loaders: [ 'babel' ]
  }
]
```

**Comment by bebraw** [comment]
Hi,

The current behavior is explained by [this test](https://github.com/survivejs/webpack-merge/blob/90cfcb29b2815b4831eee5468a7dea6bc78e12d3/test.js#L465).

The case you mention is a subset of this, though, as `exclude` is exactly the same. Based on that it would be safe to merge `loaders` so that we end up with a declaration like `loaders: ['babel', 'coffee', 'thing']`.

Do you want to PR that?

Btw, I made an initial test case for this:

```javascript
...

describe('Smart merge', function () {
  const merge = webpackMerge.smart;

  smartMergeIssueTests(merge);
  smartMergeTests(merge, 'preLoaders');
  smartMergeTests(merge, 'loaders');
  smartMergeTests(merge, 'postLoaders');
  mergeTests(merge);
});

...

function smartMergeIssueTests(merge) {
  it('should merge with exclude and loaders', function () {
    const a = {
      module: {
        loaders: [
          {
            test: /\.js$/,
            exclude: /node_modules/,
            loaders: ['babel']
          }
        ]
      }
    };
    const b = {
      module: {
        loaders: [
          {
            test: /\.js$/,
            exclude: /node_modules/,
            loaders: ['coffee', 'thing']
          }
        ]
      }
    };
    const result = {
      module: {
        loaders: [
          {
            test: /\.js$/,
            exclude: /node_modules/,
            loaders: ['babel', 'coffee', 'thing']
          }
        ]
      }
    };

    assert.deepEqual(merge(a, b), result);
  });
}

...
```

**Comment by mshwery** [comment]
@bebraw are you suggesting that we alter the current behavior to accommodate smarter merges when the `excludes` matches too?

If so, yes I'll take a stab at that.

**Comment by bebraw** [comment]
Yeah. Satisfying that test I made would be enough.

**Comment by mshwery** [comment]
So, seems like this might be a bit challenging since both allow regex values. Comparing regex can't be done plainly afaik. You would have to compare them as string values, but then they could also be arrays...

Any thoughts?

**Comment by bebraw** [comment]
[SO suggest converting to string](https://stackoverflow.com/questions/11032784/how-to-compare-two-regexps) so maybe that could work.

Good point about arrays. Consider that as a special case and test separately. `Array.isArray` should do the trick.
