### ISSUE TITLE
Could the README be updated to explain what this does?

### ISSUE THREAD

**Issue by monokrome** [survivejs/webpack-merge#23]
![jlpsm5d](https://cloud.githubusercontent.com/assets/242997/15983954/905bdf14-2f6d-11e6-916e-cac0cd672ce2.jpg)

Some users may be a bit confused regarding what this package actually does. The readme suggests that *"Normal merge function isn't that useful with webpack configuration as it will override object keys and arrays by default."*, but if you don't know what the normal merge function is in context of WebPack then it's difficult to know what this does.

**Comment by bebraw** [comment]
Yeah, that's a good point. I was thinking [lodash merge](https://lodash.com/docs#merge).

I could rephrase it like this:

> **webpack-merge** provides a `merge` function that concatenates arrays and merges objects. This behavior is particularly useful in configuring webpack. There's also a webpack specific merge variant known as `merge.smart` that's able to take webpack specifics into account (i.e., it can flatten loader definitions).

Would that help?

**Comment by monokrome** [comment]
Ooooh, yeah! That totally makes sense :) Thanks, @bebraw!
