### ISSUE TITLE
Add support for merging the `output` as well

### ISSUE THREAD

**Issue by Lucretiel** [survivejs/webpack-merge#24]
It'd be nice if, in addition to loaders, you could merge the `output` field as well. Typically, you will want to have a separate output directory, but keep the bundle name and other stuff the same.

```
// prod.config.js

const config = require('./common.config.js')
const merge = require('webpack-merge')

module.exports = merge(config, {
    output: {path: "dist.prod"}  // preserves output.filename and out output keys.
})
```

**Comment by bebraw** [comment]
It should pick up an object like that by default. Could you set up a test case to verify? If it doesn't work that way, then it's definitely something to fix.

**Comment by Lucretiel** [comment]
I'll do a quick test and be sure. Admittedly, I was assuming that webpack-merge does a shallow merge except for loaders. Does it also do the array concat behavior with plugins?

**Comment by bebraw** [comment]
Yeah, it's not limited to `loaders` only. The behavior is general so it will concat plugin definitions as well.

`merge.smart` does something extra with `loaders` but often just `merge` is enough.
