### ISSUE TITLE
Plugins overwrite each other when same plugin used

### ISSUE THREAD

**Issue by paazmaya** [survivejs/webpack-merge#29]
Given this example:

```js
const a = {
  plugins: [
    new webpack.ProvidePlugin({
      $: 'jquery'
    })
  ]
};

const b = {
  plugins: [
    new webpack.ProvidePlugin({
      Promise: 'bluebird'
    })
  ]
};

const c = merge(a,b);
```

It would seem that the `c` only has the plugins defined in `b` since they are of the same plugin provider.

Would there be a way to have them becoming the following result?

```js
const c = {
  plugins: [
    new webpack.ProvidePlugin({
      $: 'jquery'
    }),
    new webpack.ProvidePlugin({
      Promise: 'bluebird'
    })
  ]
};
```

or merged to:

```js
const c = {
  plugins: [
    new webpack.ProvidePlugin({
      $: 'jquery',
      Promise: 'bluebird'
    })
  ]
};
```

**Comment by bebraw** [comment]
Hi,

It should write

```javascript
const c = {
  plugins: [
    new webpack.ProvidePlugin({
      $: 'jquery'
    }),
    new webpack.ProvidePlugin({
      Promise: 'bluebird'
    })
  ]
};
```

given it concatenates arrays. If it doesn't, then there's something clearly wrong. Feel free to write a test case showing this. 👍 

Doing the latter won't be possible as I would need to introspect the plugins. As far as I understand, there's no way for doing that. Even then you wouldn't want to merge plugins like that in every case and instead might want to keep them separate.

**Comment by paazmaya** [comment]
Wrote a few test cases, could not get it failing....

After starting to splitting the original cause (massive configuration file) to a smaller hunks, found out that `plugins` was not in one place a direct property of the given config object, hence not available for the expected merge.

I shall close this since it was not originating from this project. Thank you and I shall give you a 🍺 next time we meet.

**Comment by bebraw** [comment]
No probs.

Note that [webpack-validator](https://www.npmjs.com/package/webpack-validator) can catch cases like that for you.

**Comment by paazmaya** [comment]
Thank you sir!

**Comment by pavel06081991** [comment]
@bebraw, is it possible to get only the instance of the same plugin from the last config after merging?

For example we have:
```
const a = {
  plugins: [
    new webpack.ProvidePlugin({
      $: 'jquery'
    })
  ]
};

const b = {
  plugins: [
    new webpack.ProvidePlugin({
      Promise: 'bluebird'
    })
  ]
};

const c = merge(a,b);
```
and after merging "a" and "b" I want "c" to be:

```
const c = {
  plugins: [
    new webpack.ProvidePlugin({
      Promise: 'bluebird'
    })
  ]
};
```

**Comment by bebraw** [comment]
@pavel06081991 It's possible to do something like this:

```javascript
const a = {
  plugins: [
    new webpack.ProvidePlugin({
      $: 'jquery'
    })
  ]
};

const b = {
  plugins: [
    new webpack.ProvidePlugin({
      Promise: 'bluebird'
    })
  ]
};

const emptyPlugins = {
  plugins: []
};

const c = merge(a, emptyPlugins, b);
```

I'm not sure if I like this solution, though. If you have better ideas for what a solution should look like, I'm interested.
