### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by sapegin** [survivejs/webpack-merge#3]
Because [it’s important](http://keepachangelog.com/).

**Comment by sapegin** [comment]
> What makes unicorns cry?
> Alright…let’s get into it.
> 
> Dumping a diff of commit logs. Just don’t do that, you’re helping nobody.

:sob:

**Comment by bebraw** [comment]
So I should maintain a changelog per hand for each project?

**Comment by sapegin** [comment]
Yes, as any other good developer do.

**Comment by bebraw** [comment]
I'm not that good. I'll leave it as is for now.

**Comment by bebraw** [comment]
Changelog is maintained manually now. Far better. Thanks. :+1:

**Comment by sapegin** [comment]
:shipit:
