### ISSUE TITLE
.smart() cause unwanted loader sequence

### ISSUE THREAD

**Issue by e-cloud** [survivejs/webpack-merge#31]
as loaders are run with the loaders array ascendingtly, smart merging reverse the config merging order, that would break some loader overload functionality.

**Comment by bebraw** [comment]
Can you give a concrete example?

**Comment by e-cloud** [comment]
To be brief, only show loader related config:

```js
const config1 = {
    module: {
        loaders: [{
            test: /\.html$/,
            loader: 'html?attrs=link:href img:src use:xlink:href'
        }]
    }
}

const config2 = {
    module: {
        loaders: [{
            test: /\.html$/,
            exclude: /index\.html/,
            loaders: [`ngtemplate`, 'html?attrs=link:href img:src source:src']
        }]
    }
}

const out = merge.smart(config1, config2)

// follow is merge result
out === {
    module: {
        loaders: [{
            test: /\.html$/,
            exclude: /index\.html/,
            loaders: [`ngtemplate`, 'html?attrs=link:href img:src source:src']
        }, {
            test: /\.html$/,
            loader: 'html?attrs=link:href img:src use:xlink:href'
        }]
    }
}

// what is expected
out === {
    module: {
        loaders: [{
            test: /\.html$/,
            loader: 'html?attrs=link:href img:src use:xlink:href'
        }, {
            test: /\.html$/,
            exclude: /index\.html/,
            loaders: [`ngtemplate`, 'html?attrs=link:href img:src source:src']
        }]
    }
}
```

the second loader in the expected config would work, although target html files are handled again by `html-loader`

**Comment by e-cloud** [comment]
I think [this line](https://github.com/survivejs/webpack-merge/blob/master/src/index.js#L112) is the origin.

**Comment by bebraw** [comment]
Yeah, I see now. It's this way by design as loaders are evaluated from bottom to up, but I can understand it's not ideal always.

There's another issue where I discuss `merge.strategy`. Implementing that would give you the control you want.

**Comment by e-cloud** [comment]
And i find out the source use too many `concat` unneccessarily.

**Comment by bebraw** [comment]
PR welcome. 👍

**Comment by bebraw** [comment]
@e-cloud I have a proposed fix at #32. Please check that out carefully and let me know what you think.

**Comment by e-cloud** [comment]
@bebraw, sorry for late response. Looks like you change some rules.

Here is one thing i don't understand.

OLD:
```
a: loaders: ['babel']
b: loaders: ['coffee', 'foo']
>>>
c: loaders: ['babel', 'coffee', 'foo']
```

NOW in PR
```
a: loaders: ['babel']
b: loaders: ['coffee', 'foo']
>>>
c: loaders: ['coffee', 'foo', 'babel']
```

**Comment by bebraw** [comment]
@e-cloud No problem. The PR should yield the first result. Here's the [related test](https://github.com/survivejs/webpack-merge/blob/a21a03519dbf215a85e14e4d6683b1d429483e2e/test.js#L701).
