### ISSUE TITLE
Merge json files into 1 file

### ISSUE THREAD

**Issue by duongvu89** [survivejs/webpack-merge#33]
Hi guys,
How can I merge json files into 1 new json file (in another folder)? The problem is I have to do it in a Angular CLI package.
Thank you!

**Comment by bebraw** [comment]
Hi,

Do you have code somewhere? I have to understand better what you need exactly.

**Comment by duongvu89** [comment]
To be brief, I'd like to merge some files like this:
- Source: src/app/**/*-en.json & src/app/**/*-de.json
- Destination: src/i18n/en.json & src/i18n/de.json

**Comment by bebraw** [comment]
Ah, like that. Here's how I would approach it:

1. [glob](https://www.npmjs.org/package/glob) source files
2. Read the files (Node fs API)
3. Push the read files through merge (can be `webpack-merge` or some other depending on the result you want)

**Comment by duongvu89** [comment]
You are right, but I guess there is no way to write a Webpack task in Angular CLI until now.

**Comment by bebraw** [comment]
I don't know Angular CLI well enough. You could try asking those guys through an appropriate channel. 👍 

Closing. Thanks. 😄

**Comment by duongvu89** [comment]
Thank you!
