### ISSUE TITLE
Error with empty loaders

### ISSUE THREAD

**Issue by printercu** [survivejs/webpack-merge#34]
Hi, seems like I have an error:
```
$ coffee 
coffee> merge = require 'webpack-merge'
Expression assignment to _ now disabled.
{ [Function] smart: [Function: webpackMerge] }
coffee> merge {module: loaders: [1]}, {module: loaders: [2]}
{ module: { loaders: [ 1, 2 ] } }
coffee> merge {module: loaders: [1]}, {module: loaders: []}
{ module: { loaders: [] } }
```
Is it expected behaviour?

__UPD__ "webpack-merge": "0.15.0"

**Comment by bebraw** [comment]
Looks like it comes from here https://github.com/survivejs/webpack-merge/commit/720567d79305a4b0fdb25016accd7e63687fe6ed . The reasoning is that you can empty earlier state this way.

I don't mind changing it if we can figure out a better design. The behavior should be documented at the readme at least.

**Comment by printercu** [comment]
Got it. Thanks!
