### ISSUE TITLE
Webpack 2 Compat

### ISSUE THREAD

**Issue by mAAdhaTTah** [survivejs/webpack-merge#35]
Is this compatible with webpack 2? Specifically, they're called "module.rules" now, instead of "module.loaders". Will this work with the new configuration?

**Comment by bebraw** [comment]
`merge.smart` needs a tiny tweak, but apart from that it should be fine as the basic idea is generic. I even used it with some karma setup myself.

**Comment by bebraw** [comment]
Included in `0.16.0`. Let me know how it goes.
