### ISSUE TITLE
'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by mikecousins** [survivejs/webpack-merge#36]
I'm getting the following error when I try webpack-merge 0.15 or 0.16. I don't see this error on 0.14.1. Any ideas what's going on?

> ERROR in ./src/js/client.jsx
> Module build failed: SyntaxError: c:/GitHub/web/front-end/src/js/client.jsx: 'import' and 'export' may only appear at the top level (3:0)
> 
>   1 | /* REACT HOT LOADER */ if (module.hot) { (function () { var ReactHotAPI = require("c:\\GitHub\\web\\front-end\\node_modules\\react-hot-api\\modules\\index.js"), RootInstanceProvider = require("c:\\GitHub\\web\\front-end\\node_modules\\react-hot-loader\\RootInstanceProvider.js"), ReactMount = require("react/lib/ReactMount"), React = require("react"); module.makeHot = module.hot.data ? module.hot.data.makeHot : ReactHotAPI(function () { return RootInstanceProvider.getRootInstances(ReactMount); }, React); })(); } try { (function () {
>   2 |
> > 3 | import React from 'react';
>     | ^
>   4 | import { render } from 'react-dom';
>   5 | import { Router, Route, IndexRedirect, browserHistory } from 'react-router';
>   6 | import 'babel-polyfill';`

**Comment by bebraw** [comment]
Hi,

I would need some code to run to say anything concrete. Could you set up a little project to study?

**Comment by mikecousins** [comment]
It seems like it's based on the ordering changes with merging now.

Our code is:
>  module: {
    loaders: [
      // javascript
      {
        test: /\.jsx?$/,
        loaders: ['babel'],
        exclude: /node_modules/,
      },
      // css
      {
        test: /\.css$/,
        loaders: ['style', 'css?sourceMap', 'myth-webpack'],
      },
      // fonts
      {
        test: /\.(ttf|eot|svg|woff(2)?)(\?[a-z0-9=&.]+)?$/,
        loader: 'file',
      },
      // images
      {
        test: /\.(jpg|jpeg|png|gif|ico)?$/,
        loader: 'file',
      },
    ],
  },

Then later:
> // if we are running the app we want to enable hot loading
if (TARGET === 'start') {
  merged = merge.smart(merged, {
    entry: [
      'webpack-dev-server/client?http://localhost:3000',
      'webpack/hot/only-dev-server',
    ],
    output: {
      publicPath: 'http://localhost:3000/',
    },
    module: {
      loaders: [
        // javascript
        {
          test: /\.jsx?$/,
          loaders: ['react-hot'],
          exclude: /node_modules/,
        },
      ],
    },
    plugins: [
      new webpack.HotModuleReplacementPlugin({
        multiStep: true,
      }),
    ],
    devServer: {
      port: 3000,
      historyApiFallback: true,
      hot: true,
    },
    debug: true,
    devtool: 'eval-source-map',
  });
}

This results in the following merged loaders:
0.14.1:
> [ { test: /\.(jpg|jpeg|png|gif|ico)?$/, loader: 'file' },
  { test: /\.(ttf|eot|svg|woff(2)?)(\?[a-z0-9=&.]+)?$/,
    loader: 'file' },
  { test: /\.css$/,
    loaders: [ 'style', 'css?sourceMap', 'myth-webpack' ] },
  { test: /\.jsx?$/,
    loaders: [ 'babel', 'react-hot' ],
    exclude: /node_modules/ } ]

0.17.0:
> [ { test: /\.jsx?$/,
    loaders: [ 'react-hot', 'babel' ],
    exclude: /node_modules/ },
  { test: /\.css$/,
    loaders: [ 'style', 'css?sourceMap', 'myth-webpack' ] },
  { test: /\.(ttf|eot|svg|woff(2)?)(\?[a-z0-9=&.]+)?$/,
    loader: 'file' },
  { test: /\.(jpg|jpeg|png|gif|ico)?$/, loader: 'file' } ]

As you can see the order of the loaders is reversed which causes this error. Is there a better way I should be doing this? I've tried using merge instead of merge.smart like this:

> // if we are running the app we want to enable hot loading
if (TARGET === 'start') {
  merged = merge(merged, {
    module: {
      loaders: [
        // javascript
        {
          test: /\.jsx?$/,
          loaders: ['react-hot', 'babel'],
          exclude: /node_modules/,
        },
      ],
    },
  });
  merged = merge.smart(merged, {
    entry: [
      'webpack-dev-server/client?http://localhost:3000',
      'webpack/hot/only-dev-server',
    ],
    output: {
      publicPath: 'http://localhost:3000/',
    },

    plugins: [
      new webpack.HotModuleReplacementPlugin({
        multiStep: true,
      }),
    ],
    devServer: {
      port: 3000,
      historyApiFallback: true,
      hot: true,
    },
    debug: true,
    devtool: 'eval-source-map',
  });
}

But that results in a duplicate js entry:
> [ { test: /\.jsx?$/,
    loaders: [ 'babel' ],
    exclude: /node_modules/ },
  { test: /\.css$/,
    loaders: [ 'style', 'css?sourceMap', 'myth-webpack' ] },
  { test: /\.(ttf|eot|svg|woff(2)?)(\?[a-z0-9=&.]+)?$/,
    loader: 'file' },
  { test: /\.(jpg|jpeg|png|gif|ico)?$/, loader: 'file' },
  { test: /\.jsx?$/,
    loaders: [ 'react-hot', 'babel' ],
    exclude: /node_modules/ } ]

**Comment by mikecousins** [comment]
I got it going by actually clearing out the loaders entirely and then putting them all back in in the if (TARGET === 'start') section. Pretty hacky. What's a better way to merge these?

**Comment by bebraw** [comment]
@mikecousins Yeah, I can see what's going on. Fix: define Babel and react-hot-loader in the same `loaders` block. You will end up with some duplication.

That said, I think I'll add `merge.strategy({ entry: 'module.loaders' })` so you can get the old behavior for loaders without changing a thing.

**Comment by mikecousins** [comment]
That would be great. 👍

**Comment by bebraw** [comment]
@mikecousins I added `merge.strategy({ entry: 'module.loaders' })` and `merge.smartStrategy({ entry: 'module.loaders' })` to `0.18.0`. I believe either should work for your case. Latter folds the configuration just like `merge.smart` except you have more control this time.

**Comment by bebraw** [comment]
Closing. I think the use case should be covered now. Thanks for the discussion. 👍
