### ISSUE TITLE
Support merging Webpack 2 Rule.use

### ISSUE THREAD

**Issue by rockmacaca** [survivejs/webpack-merge#38]
Here are the relevant docs:

https://webpack.js.org/configuration/module/#rule-use

At the surface level, the `use` property can be treated exactly the same as `loader`/`loaders` (by being added to `isLoader(key)`) and that would solve most cases, but there's a lot of room for improvement since `use` can only be top-level in the rules list.

**Comment by bebraw** [comment]
Could you write a couple of test cases? No need to be code even, just configuration. That would help a lot in implementing this correctly.

**Comment by rockmacaca** [comment]
Yeah, I'm still trying to even think what the best way to go about this will be. Here's an easy one (let's assume configs being merged will always be using `use` instead of `loaders` at the top level:

source module config:
```javascript
module: {
  rules: [
    {
      test: /\.css$/,
      use: ['style-loader', 'css-loader']
    }
  ]
}
```
additional config example 1:
```javascript
module: {
  rules: [
    {
       test: /\.css$/,
       use: extractTextLoader // this is a string loader
    }
  ]
}
```
^ Since `use` is a string, it replaces the list provided in the source. .it were an array, it would be appended.

more complicated, additional config example 2:
```javascript
module: {
  rules: [
    {
       test: /\.css$/,
       use: [
         {
           loader: 'css-loader',
           options: { 'sourceMap': true }
         }
      ]
    }
  ]
}
```
should result in
```javascript
module: {
  rules: [
    {
       test: /\.css$/,
       use: [
         'style-loader',
         {
           loader: 'css-loader',
           options: { 'sourceMap': true }
         }
      ]
    }
  ]
}
```

**Comment by rockmacaca** [comment]
So, just to keep the implementation sane, I highly recommend expanding `use` entries in the form
```javascript
use: [ 'style-loader' ]
```
to
```javascript
use: [ { loader: 'style-loader' } ]
```
since they are equivalent and it would make merging loaders more predictable. Additionally, we could extend this further by transforming top-level `loader`/`loaders` fields into `use` entries, but that would involve detecting Webpack 2 from Webpack 1 configs to keep backward compatibility.

**Comment by bebraw** [comment]
Yeah, that looks fairly complex! I would actually expect `use: extractTextLoader` to override given it's different type.

I agree some kind of an expansion step would make this easier.

If you have time, feel free to write actual tests. The repository setup is fairly straight-forward. You need to run watcher and off you go.

I'll resolve this for 1.0 release in any case. 👍

**Comment by rockmacaca** [comment]
Looking at the docs more carefully, it looks like it's invalid to have `use` be anything other than an array, instead `loader` should be used as a shortcut. Regardless, I actually need this functionality so I may even attach a full PR.

**Comment by rockmacaca** [comment]
I'm almost done with a mostly usable fix for this, but I stumbled on [`RuleSet.normalizeRules`](https://github.com/webpack/webpack/blob/master/lib/RuleSet.js#L80), which seems like it could be incredibly useful.

However, using it would require adding webpack 2 as a peer dependency, which is probably undesirable. Just wondering what your thoughts were on that. Maybe save that for a 2.x release when webpack 2 is out of beta?

**Comment by bebraw** [comment]
@rockmacaca I'll poke Tobias about that. Maybe it would work as a standalone module. Good find!

**Comment by bebraw** [comment]
@rockmacaca Maybe the coolest thing to do would be to actually fold webpack configuration at webpack core level? That would drop the need for `merge.smart` and variants. You could still `merge` as usual of course.

**Comment by rockmacaca** [comment]
That's along the lines of what I was thinking. If every source gets passed through the normalize function, lodash's merge shouldn't need too much help. I can't see how we could completely drop `merge.smart` since lodash's won't be able to merge loader options, unless you're seeing something I'm not.

Also, it looks like the equivalent webpack 1 feature is the `LoaderList` class constructor.

**Comment by bebraw** [comment]
> That's along the lines of what I was thinking. If every source gets passed through the normalize function, lodash's merge shouldn't need too much help. I can't see how we could completely drop merge.smart since lodash's won't be able to merge the array of loaders, unless you're seeing something I'm not.

I mean literally moving the folding idea to webpack core so it does the work. 👍

**Comment by bebraw** [comment]
@rockmacaca Can you try to get some performance measurements out of regular merge vs. smart merge? I just realized we could avoid quite a bit of trouble by **dropping** the smart variant if there is no difference. And if there is, that's a good reason to improve webpack internals.
