### ISSUE TITLE
Check for uniqueness when appending arrays

### ISSUE THREAD

**Issue by insin** [survivejs/webpack-merge#4]
Should webpack-merge check that it's not creating duplicate items when concatenating arrays?

I can't think of a situation where you would want that.

**Comment by bebraw** [comment]
Is there some neat way to achieve in a generic manner?

It's valid that you can have two same plugins with different parameters. The method should be able to take this into account.

**Comment by insin** [comment]
I was only thinking of strings, it gets much less fun if you start thinking about nested arrays and objects.

This is in the context of taking user config and applying it to a configuration, so perhaps validation of the generated config is a better solution in my case.

**Comment by bebraw** [comment]
Ok. If you want a check like that, I don't mind merging a PR.

Speaking of validation, I have a [specification](https://github.com/survivejs/webpack-doctor/issues) for this. I discussed about it with @sokra. Ideally we'll just push all/most of that to webpack level as then we get better UX.

**Comment by bebraw** [comment]
There's smart merging in place now. See #5 and the README for the exact behavior.
