### ISSUE TITLE
Stange merge behavior for the version 2.0.0

### ISSUE THREAD

**Issue by nasushkov** [survivejs/webpack-merge#50]
I've installed version 2.0.0 and the `merge` function returns the last object in parameters without any merging behavior applied.  I just wonder is it a bug or something have changed in the API. For the previous version it worked for me. Here is an example To illustrate my issue:

```
module.exports = merge (baseConfig, {
    devtool: false,
    entry: {
        app: [
            'babel-polyfill',
            APP_PATH
        ]
    }
})
```

module.exports is filled with the last object

**Comment by bebraw** [comment]
Hi,

What was it? Can you add `baseConfig`?

**Comment by bebraw** [comment]
Ah, I see now. `devtool` most likely (that breaking change). `merge.strategy` or composing differently would work.

**Comment by nasushkov** [comment]
Hi Juho, thanks for your response. At the end, it was a bug in my code, so I closed the issue immediately as I found it out.

**Comment by bebraw** [comment]
Ok, cool to hear you resolved it. 👍
