### ISSUE TITLE
Smart merge causes plugin like CopyWebpackPlugin to be removed

### ISSUE THREAD

**Issue by thebuilder** [survivejs/webpack-merge#56]
Upgrade to webpack-merge 2.2.0, and it caused the CopyWebpackPlugin to fail.

Looking at the merged "plugins" array in 2.0.0, the CopyWebpackPlugin is listed as `{ apply: [Function: apply] },` where other plugins look like: `UglifyJsPlugin {
    options: 
     { sourceMap: true,
       compress: [Object],
       mangle: [Object],
       output: [Object] } }`

In 2.2.0. the reference to the CopyWebpackPlugin function is removed from the array.

Should a plugin like this be something the smart merging should handle?

**Comment by bebraw** [comment]
Can you provide a minimal configuration to show the behavior? I have a feeling `CopyWebpackPlugin` might do something a little different.

**Comment by thebuilder** [comment]
Something like this:

```js
const appConfig = merge.smart(require('./tools/webpack/prod.config'), {
    name: 'client',
    entry: {
      client: ['./src/client'],
    },
    output: getOutput(),
    plugins: [
      new CopyWebpackPlugin([{
        context: config.paths.static,
        from: '**/*',
        to: config.paths.dist,
      }]),
    ]
  })
```

**Comment by bebraw** [comment]
Yeah, I see now. `CopyWebpackPlugin` does `function CopyWebpackPlugin(patterns = [], options = {}) {`which is something the other plugins don't do. This needs some special handling.

Thanks for the report. I'll try to fix this up. Most likely it takes an extra check to account for the pattern they are using.

**Comment by bebraw** [comment]
I cleared up the implementation and added a test case against this.

I understand now why it gives what it gives for the plugin. Consider the code below:

```javascript
import CopyWebpackPlugin from 'copy-webpack-plugin';

const plugin = new CopyWebpackPlugin();

console.log(plugin); // { apply: [Function: apply] }
```

This happens because `CopyWebpackPlugin` gets applied by the call. So there's not much I can do in the merge algorithm itself.

It doesn't do any assumptions based on plugin type (class, function) now, so it should be able to deal with arbitrary cases like this.

**Comment by thebuilder** [comment]
Awesome - Thanks for quick response and action. 🥇
