### ISSUE TITLE
Extract the core functionality to a package of its own

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack-merge#59]
The core (non-webpack specific) should go to another package. The idea is useful beyond webpack after all.

**Comment by chinesedfan** [comment]
I searched from npm and found 2 candidates,

- https://github.com/TehShrike/deepmerge, supports any kinds of merging as long as `options.customMerge` is provided 
- https://github.com/mesqueeb/merge-anything, supports to merge anything but without custom ability, which can be used to inspire more powerful merging strategies

**Comment by bebraw** [comment]
I've changed some of the core functionality to use **clone-deep**. The rest can be maintained in this package.
