### ISSUE TITLE
Future - Revise API 

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack-merge#61]
It could be a nice move to go "all in" with the customization API and decrease the API surface a notch in favor of a good extension point. Example:

```javascript
merge(
  merge.unique(
    'plugins',
    IGNORE_PLUGINS,
    plugin => plugin.constructor && plugin.constructor.name
  ),
  merge.strategy({
    entry: 'prepend', // or 'replace', defaults to 'append'
    'module.loaders': 'prepend'
  }),
  merge.smart()
)(...);
```

Composed from top to bottom (could go from bottom to top Redux style too). First returning function wins.

The old `merge` would remain the same. It's the extra functionality that would have more room to grow. It actually goes a bit like this internally already.

The only problem is going to be the smart variant of strategy and particularly its `prepend` functionality. Strategies could become more granular like this to work around the problem:

```javascript
merge(
  merge.unique(
    'plugins',
    IGNORE_PLUGINS,
    plugin => plugin.constructor && plugin.constructor.name
  ),
  merge.strategy('entry', 'prepend'),
  merge.smartStrategy('module.loaders', 'prepend')
)(...);
```

**Comment by VladimirGrenaderov** [comment]
@bebraw,  what about solution to transparently merge plugins options? It could be like a small wrapper:

```javascript
const Wrapper = function(c, o) {
    return new c(o);
};

const SomePlugin = require('some-plugin');
...
plugins: [
    new Wrapper(/* constructor */ SomePlugin, /* options */ { opt1: 1 })
]
...
plugins: [
    new Wrapper(/* constructor */ SomePlugin, /* options */ { opt2: 2 })
]

// result:  new Wrapper(SomePlugin, { opt1: 1, opt2: 2 })

```
I have ~20 separate configs, and have to place some plugins (like localization) in one config instead of split them to common and override options in dev / prod.

**Comment by bebraw** [comment]
@VladimirGrenaderov I've tried plugin option merging in the past. While feasible, it's a little tricky problem as you have to clone/merge within prototype chains and you also have function style plugins that need special treatment (functions that return apply). That said, doing this as a plugin for `merge` would make tons of sense. Thanks for the idea. 👍

**Comment by adrienharnay** [comment]
Hey, is it currently possible to use unique AND strategy at the same time? Can't figure out how

**Comment by bebraw** [comment]
@adrienharnay In v5 I expose `mergeWithCustomize` that works with `unique`. Technically strategies use `mergeWithCustomize` underneath and I'll make sure to expose the composition so it's possible to customize.

**Comment by adrienharnay** [comment]
Ok thank you!

**Comment by bebraw** [comment]
@adrienharnay Ping me at an issue with a specific example if there's something confusing in the API. I'll push the first beta of v5 very soon!

**Comment by bebraw** [comment]
@adrienharnay Ok, it's out now - you can install it using `npm add webpack-merge@beta`. That will pull v5. There's an issue for feedback at #136.
