### ISSUE TITLE
Webpack2: prepend use array configuration

### ISSUE THREAD

**Issue by derekdon** [survivejs/webpack-merge#64]
System info
webpack-merge@2.4.0
Chrome Version 53.0.2785.116 m
Node 6.3.1
NPM 3.10.3
Windows 7 Professional

```
// Common config
module: {
	rules: [
		{
			test: /\.js$/,
			exclude: /(node_modules|lib)/,
			use: [
				{
					loader: 'babel-loader',
					options: {
						cacheDirectory: true
					}
				}
			]
		}
	]
}
...
// Prod config
module: {
	rules: [
		{
			test: /\.js$/,
			use: [
				{
					loader: 'string-replace-loader',
					options: {
						multiple: [
							{
								search: /["']ngInject["'];*/,
								replace: '',
								flags: 'g'
							}
						]
					}
				},
				'ng-annotate-loader'
			]
		}
	]
}
```

The following is the desired output:

```
module: {
	rules: [
		{
			test: /\.js$/,
			exclude: /(node_modules|lib)/,
			use: [
				{
					loader: 'string-replace-loader',
					options: {
						multiple: [
							{
								search: /["']ngInject["'];*/,
								replace: '',
								flags: 'g'
							}
						]
					}
				},
				'ng-annotate-loader',
				{
					loader: 'babel-loader',
					options: {
						cacheDirectory: true
					}
				}
			]
		}
	]
}
```
I'm not 100% sure what the correct settings are to achieve this. Could you advise? I've tried a couple of options. ie.

```
let mergeOutput = webpackMerge.smartStrategy(
        {
            // rules: 'prepend',
            'module.rules.use': 'prepend',
            plugins: 'append'
        }
    )(common, prod);
```

**Comment by bebraw** [comment]
It's that object -> array -> object nesting that's problematic. In the current implementation it gets only as far as `module.rules` key and terminates before.

I have to find a good fix for that. The code needs to take into account that arrays can contain objects too in this specific case.

Thanks for bringing this up. Great example.

**Comment by derekdon** [comment]
@bebraw thanks for confirming that this doesn't work currently... I'll roll a manual implementation with lodash in the meantime.

**Comment by bebraw** [comment]
@derekdon No probs. I'll see if it's a quick fix and try to get this done today.

**Comment by derekdon** [comment]
@bebraw Now that would be awesome! ...but don't worry if you don't get time.

**Comment by bebraw** [comment]
`merge.smartStrategy` should behave as you expect now. Thanks for the report.

**Comment by derekdon** [comment]
@bebraw Wow that was a quick turnaround! Thanks a million, will test it shortly. Did you get a chance to npm publish it? No worries if now, I can use github directly.

**Comment by derekdon** [comment]
@bebraw Working for me now as expected, nice! Thanks.
