### ISSUE TITLE
Removed dependency `changelog` still shows up in NPM

### ISSUE THREAD

**Issue by jnwng** [survivejs/webpack-merge#7]
hello,

been using `webpack-merge` for a project at work (thanks for writing it!). however, when attempting to [shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) my package that uses `webpack-merge`, it complains about not having the dependencies for the `changelog` module (a module previous included in webpack-merge). 

while the package is no longer included via `package.json`, it seems that the tarball of this library (found [here](http://registry.npmjs.org/webpack-merge/-/webpack-merge-0.7.1.tgz)) __does__ include `changelog` inside the node_modules folder. i suspect that you may have this folder sitting around in your local directory, and it got bundled up by npm when publishing to the registry.

any chance we can update the npm tarball to remove that dependency?

**Comment by bebraw** [comment]
Thanks for letting me know! Just published a new version without it.

It's really interesting it picked up the old dependency. I have to look into making my release process more solid.

**Comment by jnwng** [comment]
yeah, not sure how that would be caught. thanks for the quick turnaround!
