### ISSUE TITLE
webpack2 support?

### ISSUE THREAD

**Issue by weizongqi1990** [survivejs/webpack-merge#71]

**Comment by bebraw** [comment]
Hi,

webpack 2 should be supported. Are you having some problems with it?

**Comment by SalahAdDin** [comment]
@bebraw i have the same asking. And i am not sure about if i have problem with it or not.

**Comment by bebraw** [comment]
@SalahAdDin Is there some specific problem with webpack 2?

**Comment by Fardinak** [comment]
@bebraw I'm having trouble merging `module.rules.use.options`. I'd like to merge (by append) the `presets` array of the babel loader.

I did manage it using a customization function...
```javascript
  const conf = merge({
    customizeArray(a, b, key) {
      if (key === "module.rules") {
        return _.mergeWith(a, b, (a, b, key) => {
          if (key === 'presets') {
            return a.concat(b);
          }

          return undefined;
        });
      }

      return undefined;
    }
  })(common, production);
```
Is that the right way to handle it though?

**Comment by bebraw** [comment]
@Fardinak Default merge won't do anything special with array contents (just concat). So based on that your customization might be the right way. I would need more context to tell any better.

I think I'll close this issue as I never heard back from the original reporter.

**Comment by SalahAdDin** [comment]
:+1: It works fine, thanks!
