### ISSUE TITLE
Expect to run functional webpack.config

### ISSUE THREAD

**Issue by mastilver** [survivejs/webpack-merge#76]
`webpack.config.base.js`:
```js
module.exports = (env) => ({
  devtool: env.fast ? 'eval' : 'source-map',
  plugins: [
    ...
  ]
});
```

`webpack.config.js`: 
```js
const merge = require('webpack-merge');

const base = require('./webpack.config.base.js');

module.exports = merge(base, {
  output: {
    filename: '[name].js'
  }
});
```

Running: `webpack --env.fast`, I expect the generated webpack.config to be:

```js
module.exports = {
  devtool: 'eval',
  output: {
    filename: '[name].js'
  },
  plugins: [
    ...
  ]
}
```

----- 
I can start working on a fix tonight

**Comment by bebraw** [comment]
The problem is that **webpack.config.base.js** is disconnected. One way to solve it:

**webpack.config.js**

```javascript
...

module.exports = (env) => merge(base(env), {
  output: {
    filename: '[name].js'
  }
});
```

You may have to adapt a bit but it's important you pass `env` to base somehow.

**Comment by mastilver** [comment]
Yeah... I don't know why I didn't think of doing that in the first place :$

Thank you!
