### ISSUE TITLE
Seems Webpack 2.* ExtractTextPlugin loader syntax smart merging is not working

### ISSUE THREAD

**Issue by thekip** [survivejs/webpack-merge#78]
Assume we have `webpack.common.js` with follow loader section:
```js
//...
   module: {
        rules: [
	//...
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: [
                        {
                            loader: 'css-loader',
                            options: {
                                import: false,
                                url: false,
                                sourceMap: true,
                            },
                        },
                    ],
                }),
	    //...
            },
        ],
    },
//...
```

And in `weback.test.js` I want override this css loader typing: 

```js
var merge = webpackMerge.smart
return merge(commonConfig, {
        module: {
            rules: [
                {
                    test: /\.css$/,
                    use: [{
                        loader: 'null-loader',
                    }],
                },
            ],
        },
}
```

I get the following error: 

> TypeError: entry.loader.match is not a function
    at uniteEntries (\node_modules\webpack-merge\lib\join-arrays-smart.js:130:42)
    at arrayIncludesWith \node_modules\lodash\_arrayIncludesWith.js:15:9)

The root cause is in the new ExtractTextPlugin syntax, which is not an array, or string, but it is a function written to loader property.

**Comment by bebraw** [comment]
I wonder what's the right fix. Maybe detect the parent function, execute the function, try to merge the output, amd wrap back?

**Comment by thekip** [comment]
for my case enough just replace this loader with new one. I'm not sure for other cases. 
But your proposed solution sounds too complicated...

**Comment by bebraw** [comment]
Yeah, I need something generic. It's a little tricky.

**Comment by thekip** [comment]
By the way, if somebody find this discussion from google, there is another solution (how to override css loader for test environment)

Put in your `webpack.test` config in plugin section
```js
/**
 * Remove all those files from tests
 */
new NormalModuleReplacementPlugin(/\.(gif|png|scss|css)$/, 'lodash/noop'),
```
You can use instead `lodash/noop`, `node-noop`, or any other available in your application.

**Comment by bebraw** [comment]
@thekip That's a nice solution. Maybe this is actually a documentation issue?

**Comment by rockmacaca** [comment]
This isn't an issue with this project. The plugin's docs might have been updated since this issue was created but [the example it gives upfront](https://github.com/webpack-contrib/extract-text-webpack-plugin) uses `use` instead of `loader` for the key. That should fix the issue here.

If you ran your config already merged, webpack should be giving you something along the lines of
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[2].use should be one of these:
  non-empty string | function | object { loader?, options?, query? } | ...
```

I believe ExtractTextPlugin returns an object of the form `{ loader: '/home/.../loader.js, ... }`, which is obviously not allowed underneath the `loader` key in the schema.

**Comment by sqfbeijing** [comment]
Yes, I have encountered the same problem. In webpack.common.js , I write this: 
```
			{
				test: /\.css$/,
				use: [
					{
						loader: 'style-loader' // creates style nodes from JS strings
					},
					{
						loader: 'css-loader' // translates CSS into CommonJS
					},
					{
						loader: 'postcss-loader'
					}
				]
			},
```
In webpack.prod.js , I write this:
```
			{
				test: /\.css$/,
				use: ExtractTextPlugin.extract({
					fallback: 'style-loader',
					use: ['css-loader', 'postcss-loader']
				})
			},
```
I use merge.smart() function, I want it only remain the last one , but it didn't work as I expected. 
So I remove it(the first one) from webpack.common.js, add to webpack.dev.js, and it work.  But is there any better approach？ @thekip @bebraw   Thanks too much.

**Comment by BFdes** [comment]
I've also had to use the same approach as @sqfbeijing. 
In my case its not that big a deal since I won't have too many environments to cater for (dev, prod, test).

**Comment by bebraw** [comment]
@sqfbeijing It's tricky. I would push both behind a function or something to merge and then compose based on target. Less magic and cleaner as well.

**Comment by bebraw** [comment]
I'll drop support for `merge.smart` and `merge.smartStrategy` in the next major version as it's tricky to support due to different webpack versions and overall complexity.

Can you rewrite the configuration in terms of regular `merge` or `mergeStrategy`? I use solely `merge` for all of my personal work as it's predictable.
