### ISSUE TITLE
Smart Merging Webpack2 rules rearranges loader rule array, thus breaking the loader/rule 

### ISSUE THREAD

**Issue by eomuraliev** [survivejs/webpack-merge#79]
1. webpack-merge version 4.1.0. Node version 6.10.3. Webpack 2
2. Please see the repo I created to demonstrate the issue at https://github.com/eomuraliev/webpack-merge-bug-webpack2-rules.
 In short, smart merge does not properly handle webpack 2's `rules` based loader merging. See how `style_loader` gets moved to be the 2nd item in the merged rule, instead in the beginning of the array.

**Comment by oatkiller** [comment]
Having the same issue

**Comment by bebraw** [comment]
Thanks for bringing this up. Anyone up for a PR? The source is heavily tested.

**Comment by bebraw** [comment]
That said, maybe the actual solution would be to deprecate smart merge. It would need some benchmarking but if there's no noticeable difference in runtime speed, it would be good to drop it.

**Comment by jasonmacdonald** [comment]
Having the same issue with reordering... is there a solution here? Using just merge() means I end up with duplicated rules.

**Comment by rockmacaca** [comment]
I tracked this down to the recent addition for supporting inserting loaders relative to others. IMO, #70 shouldn't have been merged. The use-case he was suggesting could have been easily solved with the 'replace' merge strategy.

Detecting what order to insert loaders relative to others that might be present is not trivial, and the implementation breaks the append strategy.

**Comment by rockmacaca** [comment]
Yeah, I've been thinking about it some more and it's just too ambiguous for my taste. Consider the case:
```javascript
const base = {
  module: {
    rules: [{ use: ['one-loader', 'two-loader', 'three-loader'] }]
  }
}
const mixin = {
  module: {
    rules: [{ use: ['three-loader', 'one-loader'] }]
  }
}
```
Would the result be
```javascript
{
  module: {
    rules: [{ use: ['two-loader', 'three-loader', 'one-loader'] }]
  }
}
```
or
```javascript
{
  module: {
    rules: [{ use: ['three-loader', 'one-loader', 'two-loader'] }]
  }
}
```
or even
```javascript
{
  module: {
    rules: [{ use: ['three-loader', 'two-loader', 'one-loader'] }]
  }
}
```
?
All three keep the new order, but precisely what should happen isn't well-defined. If there is a config that needs loaders to be both appended _and_ prepended, two separate merges should happen using the appropriate strategies, at least in my opinion.

**Comment by bebraw** [comment]
Yeah, separate strategies might be the way. Better document that.
