### ISSUE TITLE
Handle returned Promises

### ISSUE THREAD

**Issue by defrex** [survivejs/webpack-merge#81]
Webpack 2 supports returning a Promise from the config function.

https://webpack.js.org/configuration/configuration-types/#exporting-a-promise

This currently isn't supported by `webpack-merge`.

**Comment by bebraw** [comment]
How would you expect this case to work? Can you give an example of where you are using it?

**Comment by defrex** [comment]
Currently, I'm performing an async request for a GraphQL schema when generating my base webpack config.

Ideally the sub-configs would just wait for the promise to resolve and then be merged, similar to function-based resolving. Rough sketch:

```js
function merge (baseConfig, childConfig) {
  if (baseConfig instanceof Function) {
    const resolved = baseConfig()
    if (resolved instanceof Promise) {
      return resolved.then((result) => merge(result, childConfig))
    } else {
      return merge(resolved, childConfig)
    }
  } else {
    // etc
  }
}
```

**Comment by bebraw** [comment]
Alright. I could accept a PR for the feature. Please write nice tests. 👍

**Comment by VadimDez** [comment]
Any further updates?

**Comment by bebraw** [comment]
No updates. Still waiting for a PR to review.

**Comment by defrex** [comment]
My need for this went away. We decided to make graph inspection it's own step so the changes appear in PRs, thus I don't need my webpack config to be async. I'm not likely to submit a PR.

**Comment by simondiep** [comment]
At the very least, add better messaging if this happens.  I spent countless hours trying to figure out the cryptic error message only to find out I was using webpack-merge with a promise.

Current cryptic message:
```
Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: 5257bb310847f73aa6a9
Version: webpack 4.16.0
Time: 55ms
Built at: 2019-02-22 12:56:40

ERROR in Entry module not found: Error: Can't resolve './src' in '/git/delete-me/console'
```

**Comment by Stijnkool** [comment]
I have found a solution that does not require `webpack-merge` to support promises:

This does not work:
```js
module.exports = merge(someConfig, async () => ({
  prop: await someFunc()
}));
```

This does work:
```js
module.exports = async () => {
  const value = await someFunc();
  return merge(someConfig, { prop: value });
};
```
I am not sure if this solves every problem out there. But it solved mine.

**Comment by bebraw** [comment]
I will throw an error in this case at v5 (#135). It's likely best to wrap `merge` within a `Promise` at the user space as that avoids complexity though I can still accept a PR at a later time.
