### ISSUE TITLE
Help with new types for webpack-merge

### ISSUE THREAD

**Issue by srghma** [survivejs/webpack-merge#84]
Hi, creator, Im making types for webpack-merge, [so far I have this](https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...BjornMelgaard:webpack-merge-new), can you review? 
Especially [this](https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...BjornMelgaard:webpack-merge-new#diff-9fc0ac9743d3ce2a149add618f53cfccR45). I made smart and multiple accept array of any to make tests compatible with examples in readme

**Comment by bebraw** [comment]
Hi,

Would it make sense to port the types here? I wouldn't mind a complete TypeScript port either if you are up for it.

**Comment by BjornMelgaard** [comment]
Port - ok, will make, complete port - now I have no time, sorry

**Comment by bebraw** [comment]
No probs. There's no hurry. Let's leave this open for now in case someone wants to tackle it. 👍

**Comment by BjornMelgaard** [comment]
@bebraw , hi, I made pr, can you look https://github.com/survivejs/webpack-merge/pull/86

**Comment by bebraw** [comment]
@BjornMelgaard Yup. Likely during the weekend. Busy week for me.

**Comment by BjornMelgaard** [comment]
@bebraw , ok, no need to hurry, using my fork locally and it works))

    "webpack-merge": "git+https://github.com/BjornMelgaard/webpack-merge.git#with-ts-types"

P.S. [the only part im not sure about](https://github.com/BjornMelgaard/webpack-merge/blob/with-ts-types/index.d.ts#L39)

**Comment by bebraw** [comment]
This will get fixed in v5 (ported to TS). Sorry for the delay!
