### ISSUE TITLE
Support function-type webpack configs

### ISSUE THREAD

**Issue by meyer** [survivejs/webpack-merge#89]
Function-type config support added in webpack 2 is super useful for making conditional configs. I wrote a tiny package that wraps `webpack-merge` and adds support for merging function configs, but it seems like it could very easily be a supported feature in `webpack-merge`.

Here’s how I’d envision it working:

```js
// this needs a better name
const webpackMerge = require('webpack-merge/config-function');

const mergeStrategy = {/* ... */};

module.exports = webpackMerge.smartStrategy(mergeStrategy)(
  (env, options) => ({
    output: {
      filename: env.useHash ? '[name]-[].js' : '[name].js',
    },
  }),
  // ...
);
```

Merge functions imported from `webpack-merge/config-function` (name extremely WIP) would be the same merge functions provided by `webpack-merge`, but each function would return a _config function_ instead of a config object. This returned function would take the parameters given to it by the `webpack`/`webpack-dev-server` CLI and pass them on to each config function. Functions would be called and the result would be merged using the merge functions from `webpack-merge`. Essentially, each merge function would be a lightweight wrapper around the parent merge function.

If this is something that’s of interest to you, I can cook up a PR.

This could very easily be extended to support Promise configs as well (as mentioned in #81).

**Comment by bebraw** [comment]
Yeah, PR would be great. `Promise` bits could be another one. Thanks.

**Comment by 5arias** [comment]
Supporting function-type configs would be a huge help, currently I'm running into issues with passing custom env variables into my config via the cli. Now I'm debating whether to use webpack-merge or just run completely separate configs for local/dev/QA/prod. @meyer let me know how I can help!

**Comment by meyer** [comment]
@5arias thanks! I’ve got a rough version working and I’m in the process of updating tests (there are lots of them). Once I’ve opened a PR, I would definitely appreciate some extra eyeballs on my code.

**Comment by meyer** [comment]
@bebraw as I get further into this PR I’m realising that duplicating each function as I mentioned in my initial proposal will result in a lot of redundancy and potential for error. I’m thinking of doing something like this instead:

```js
// webpack.config.js
const { smartStrategy, functionConfig } = require('webpack-merge')
const merge = smartStrategy({/* strategy */});
module.exports = functionConfig(merge)(/* configs */);
```

`webpackMerge.functionConfig` returns a function that calls config functions. The results of the called functions are merged with the merge function passed as `functionConfig`’s first and only param.

Any thoughts?

**Comment by bebraw** [comment]
@meyer Simple design is better. No need to go for polymorphism as that would complicate things too much as you noticed.

**Comment by brettpostin** [comment]
Any update on this? Would be great to support function-type configs!

**Comment by bebraw** [comment]
@brettpostin No update yet. I tend to merge *within* functions myself. An API discussed above could work, though.

**Comment by meyer** [comment]
@brettpostin I haven’t had time to finish up the PR but I’ll try to get back to it this weekend.

**Comment by brettpostin** [comment]
No worries, don't know why I didn't think to do what @bebraw suggested but that works equally fine!

**Comment by Robula** [comment]
I thought this was what `webpack-merge` did, it says in the first paragraph of the README "If functions are encountered, it will execute them, run the results through the algorithm, and then wrap the returned values within a function again".

However from my experience this is not the case. Instead of calling `merge(configFunction, {...});` I instead call `merge(configFunction(), {...});`.

The documentation perhaps just needs a little more clarity to say that functions only execute _within_ the configuration objects and doesn't execute the parameters passed to `webpack-merge`.

**Comment by bebraw** [comment]
@Robula Yeah, that applies to functions **within** configuration (see *postcss-loader* for instance). I can accept a doc PR for that.

**Comment by zstrenfel** [comment]
Any updates? Would love this functionality.

**Comment by bebraw** [comment]
@zstrenfel It's waiting for a good PR. That said, merging *inside* a function tends to work quite well.

**Comment by mmospanenko** [comment]
In description 
"webpack-merge provides a merge function that concatenates arrays and merges objects creating a new object. **If functions are encountered, it will execute them**, run the results through the algorithm, and then wrap the returned values within a function again.".

But it doesn't work. I have only second only secong argumnet (empty object) as result:
```
const baseConfig = require('./base.config.js');
const config = merge(baseConfig, {});
console.log(config);
```
{} in stdout.

baseConfig function example (without merge works correctly):
```
module.exports = env => {
  const ver = (env && env.ver) || 'dev';
  return {
    // long config...
  };
};
```

**Comment by bebraw** [comment]
That means functions *within* configuration.

**Comment by Joonpark13** [comment]
@5arias a workaround that I'm using right now is as follows:

in my webpack.dev.js I do

```javascript
module.exports = env => merge(common(env), {
    ...
});
```

and in my webpack.common.js

```javascript
module.exports = env = ({
    ...
    ---USE env HERE---
});
```

That said, I'd love to see this functionality added!

**Comment by ptrwllrd** [comment]
@Joonpark13 You made a  typo in the common.js part. It should be:

> and in my webpack.common.js
> 
> ```js
> module.exports = env => ({

Otherwise yeah, this works and I was able to convert my config partials into functions and pass any needed --envs to them.

**Comment by Perogy** [comment]
> @5arias a workaround that I'm using right now is as follows:
> 
> in my webpack.dev.js I do
> 
> ```js
> module.exports = env => merge(common(env), {
>     ...
> });
> ```
> 
> and in my webpack.common.js
> 
> ```js
> module.exports = env = ({
>     ...
>     ---USE env HERE---
> });
> ```
> 
> That said, I'd love to see this functionality added!

This is great, thanks!

**Comment by vitalets** [comment]
> @5arias a workaround that I'm using right now is as follows:
> 
> in my webpack.dev.js I do
> 
> ```js
> module.exports = env => merge(common(env), {
>     ...
> });
> ```
> 
> and in my webpack.common.js
> 
> ```js
> module.exports = env = ({
>     ...
>     ---USE env HERE---
> });
> ```
> 
> That said, I'd love to see this functionality added!

This looks great but how do you run your builds from npm scripts?
Having 
```
"build:dev": "webpack --config webpack.dev.js --env development",
"build:prod": "webpack --config webpack.prod.js --env production"
``` 
looks like over-configuration: both `dev` / `development` and `prod` / `production` in command.

**Comment by bebraw** [comment]
> looks like over-configuration: both dev / development and prod / production in command.
> The config itself should define all needed params.

`process.env.npm_lifecycle_event` can be used to detect where the configuration was run.

I have mixed feelings about supporting function style configuration. In practice I've learned that the following kind of pattern works well with **webpack-merge**:

```javascript
const commonConfig = { ... };
const productionConfig = { ... };
const developmentConfig = { ... };

module.exports = env => {
  switch (env) {
    case 'production':
      return merge(commonConfig, productionConfig);
    case 'development':
      return merge(commonConfig, developmentConfig);
    default:
      throw new Error('No matching configuration found');
  }
}
```

The above works well with the `--env` parameter supported by webpack. The point is to merge inside the function. In case the environment is needed by one of the subconfigurations, then it's easy enough to pass it like this within the function: `commonConfig(env)`. As long as that returns something mergeable, it's going to work.

The same idea works with `Promise`s. You can return a `Promise` from the configuration file and then `merge` inside it. In v5 (#135) I'll throw an Error in case a configuration contains `Promise` itself.

**Comment by onetrev** [comment]
Thanks @bebraw that pattern works perfectly (I also noticed you added the above to the docs, so that's awesome)!

I just wanted to clarify though, this also means having your common, production, and dev configs all in the same file though instead of three files? That's what I did anyway and I really like it as I find it easier to know and see what's duplicated. Of course, in the webpack docs and all the blog posts out there they have you merging three separate files.

**Comment by bebraw** [comment]
> I just wanted to clarify though, this also means having your common, production, and dev configs all in the same file though instead of three files? That's what I did anyway and I really like it as I find it easier to know and see what's duplicated. Of course, in the webpack docs and all the blog posts out there they have you merging three separate files.

I think you can combine the both:

```javascript
const commonConfig = require('./config/common.js');
const productionConfig = require('./config/production.js');
const developmentConfig = require('./config/development.js');

module.exports = env => {
  switch (env) {
    case 'production':
      return merge(commonConfig, productionConfig);
    case 'development':
      return merge(commonConfig, developmentConfig);
    default:
      throw new Error('No matching configuration found');
  }
}
```

The module naming above is a bit arbitrary. As you mentioned, having all the configuration has some benefits to it as it's fast to scan and see what's getting composed.

There's no one strong rule to this and especially with client work I usually end up abstracting out chunks of configuration into functions I then compose together to give a degree of abstraction over what's understood. The benefit of doing this is that you can document what you are doing (esp. with TypeScript) and get a nice verbose API to use.

**Comment by brycekunkel** [comment]
Alternatively, if you want to keep your file structure the way as describe in the [webpack guide](https://webpack.js.org/guides/production/), you can pass the `env` variable as an argument to you common webpack config. 

```
/// webpack.common.js

module.exports = env => ({
module: {
...
})


///webpack.dev.js and webpack.prod.js

const { merge } = require('webpack-merge')
const common = require('./webpack.common.js')

module.exports = env => merge(common(env), {
module: {
...
}
})
```

This worked well for me.

**Comment by onetrev** [comment]
Anyone else updated to the latest webpack and webpack-cli (5.4.0 and 4.2.0 respectively) and found the [switch statement above](https://github.com/survivejs/webpack-merge/issues/89#issuecomment-669027496) now returns the default error statement no matter what? I fire up webpack from the CLI like so:

`npx webpack serve --env development --config webpack.config.js`

Any advice would be greatly appreciated!

**Comment by bebraw** [comment]
Can you set up an example to study? I recall webpack-cli may have had some API change so you might want to validate that.

Personally I've moved to webpack-nano as it's lighter and does enough. For that reason I ported my webpack book (survivejs.com/webpack) to use it.

**Comment by onetrev** [comment]
I can definitely provide sample code, but I believe the way webpack handles the environment variable is the problem. A console.log of `env` with my CLI statement above reveals this: 

`{ development: true, WEBPACK_SERVE: true }`

**Comment by bebraw** [comment]
@onetrev Yup, that's what I mean. There was some change at webpack-cli side that changed behavior. I think mode is handled somehow differently now.

**Comment by onetrev** [comment]
Sorry, I should have added I think you have to do this now. This works, just isn't as nice as the switch statement.

```
module.exports = env => {
  if (env.production) {
    return merge(commonConfig(env), productionConfig);
  } else if (env.development) {
    return merge(commonConfig(env), developmentConfig);
  } else {
    throw new Error('Merge Fail! No matching "env" configuration found');
  }
}
```

**Comment by bebraw** [comment]
@onetrev See https://webpack.js.org/api/cli/#environment-options . Maybe the trick is to do `webpack --env mode=development` and then check against `process.env.mode`. It's a bit unfortunate they changed the behavior between versions as the earlier API was more convenient.

For reference, here's what it would look like with [webpack-nano](https://www.npmjs.com/package/webpack-nano): https://survivejs.com/webpack/developing/composing-configuration/ .
