### ISSUE TITLE
Smart merging for loaders does not work when exclude option is used

### ISSUE THREAD

**Issue by dennisoelkers** [survivejs/webpack-merge#9]
As far as i can see loaders are not merged although their test is identical, when they are defining include/exclude options (see [here](https://github.com/survivejs/webpack-merge/blob/master/src/index.js#L25)).

- Is this on purpose?
- Is it possible to still merge them when include/exclude options are identical?

**Comment by bebraw** [comment]
Yeah. The current solution isn't perfect. PR would be very welcome to make the behavior more accurate.
