### ISSUE TITLE
Can't merge when exclude is missing from the value being merged

### ISSUE THREAD

**Issue by jackwilsdon** [survivejs/webpack-merge#90]
> 1. Check the version of **webpack-merge** you are using. If it's not the newest version, update and try again (see changelog while updating!).

Running `webpack-merge@4.1.0`.

> 2. If the issue is still there, write a minimal script showing the problem and expected output. You can also set up a repository (even better).

```JavaScript
const merge = require("webpack-merge");
const { inspect } = require("util");

const base = {
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        loader: "babel-loader",
        exclude: /node_modules/,
      },
    ],
  },
};

const extended = merge.smart(base, {
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        loader: "babel-loader",
        options: { presets: [ "react" ] },
      },
    ],
  },
});

console.log(inspect(extended, { depth: null, colors: true }));
```

> 3. Include the script to the issue. Mention Node version and OS in your report.

Ubuntu 17.04, node v8.4.0

---

Here is the output I'd expect (merging the `babel-loader` rules);

```JavaScript
{ module: 
   { rules: 
      [ { test: /\.jsx?$/,
          loader: 'babel-loader',
          exclude: /node_modules/,
          options: { presets: [ 'react' ] } } ] } }
```

And here's the output I'm getting;

```JavaScript
{ module: 
   { rules: 
      [ { test: /\.jsx?$/,
          loader: 'babel-loader',
          exclude: /node_modules/ },
        { test: /\.jsx?$/,
          loader: 'babel-loader',
          options: { presets: [ 'react' ] } } ] } }
```

I took a look at `merge.smartStrategy`, but couldn't work out how to allow it to merge like this.

**Comment by jackwilsdon** [comment]
Just found #68 and this;

https://github.com/survivejs/webpack-merge/blob/d9559b9d28deecd1d7887aeef67a41180b66eb78/src/join-arrays-smart.js#L17-L20

So I guess this is intended behaviour?

**Comment by bebraw** [comment]
Yeah. I see what you are trying to do, though. When it comes to Babel, I like to push the problem to `.babelrc` and set `BABEL_ENV` to match the env you pass to webpack.

@specialkk Any thoughts on this?

**Comment by specialkk** [comment]
Yeah, it's intentional. The reason for that is because there wouldn't be a straightforward way to merge rules that don't specify include/exclude vs. those that do. It's necessary because otherwise if you were to define another rule with `test: /\.jsx?$` with or without some `include` or `exclude`, it would be ambiguous which rule would actually get merged when you specify a new rule without them.

Also +1 for using `.babelrc`.

**Comment by bebraw** [comment]
I'll drop support for smart merging in v5 (see #135). It's best to refactor it to use the regular `merge` and the related utilities.
