### ISSUE TITLE
merge customization ignored when key is only present on `b`

### ISSUE THREAD

**Issue by olsonpm** [survivejs/webpack-merge#92]
I believe the code [found here](https://github.com/survivejs/webpack-merge/blob/master/src/join-arrays.js#L34-L36) should instead be:

```diff
if (isPlainObject(b)) {
-  return cloneDeep(b);
+  customizeObject(a, b, newKey);
}
```

`cloneDeep` is problematic when merging in a devServer proxy that relies on [agentkeepalive](https://www.npmjs.com/search?q=agentkeepalive).  That agent in particular is necessary to get around [an issue with NTLM auth](https://github.com/chimurai/http-proxy-middleware/issues/39#issuecomment-159841367).

The workaround I'm using now is

```js
const devConfig = merge(common, { /* dev config */ });
devConfig.devServer = getDevServerConfig();

module.exports = devConfig;
```

If this is agreeable then I will create a PR.

I appreciate all your work with webpack.

**Comment by olsonpm** [comment]
Ugh - I'm sorry for the noise.  I shouldn't raise issues when I'm tired.

Allowing customizations for keys that only exist on `b` may still be a worthwhile feature, but my solution wasn't even half-thought through and I didn't test it at all locally.  I'm also realizing it doesn't make sense to 'merge' configurations that only exist in `b`, so my workaround is semantically more correct anyway.

**Comment by bebraw** [comment]
No probs. Thanks for solving. 👍
