### ISSUE TITLE
smart merge does not merge loaders if include is defined

### ISSUE THREAD

**Issue by pietrofxq** [survivejs/webpack-merge#96]
I'm trying to prepend the loader `['style-loader']` to my dev config. The problem is that, if `include` is defined in my common file, the loader is not added. When I remove `include`, it works.

Common:

```
{
  module: {
    rules: [{
        test: /\.?global.css$/,
        include: /src/,
        use: ['css-loader', 'postcss-loader']
      }]
  }
}
```

Dev:

```
const merge = require('webpack-merge').smartStrategy({
  entry: 'prepend',
  'module.rules.use': 'prepend'
})

merge(common, {
  module: {
    rules: [{
        test: /\.?global.css$/,
        use: ['style-loader']
      }]
  }
})

```

Expected:

```
{ 
  test: /\.?global.css$/,
  include: /src/,
  use: [ 'style-loader', 'css-loader', 'postcss-loader' ] 
}
```

Actual result:

```
{ 
  test: /\.?global.css$/,
  include: /src/,
  use: [ 'css-loader', 'postcss-loader' ] 
}
``` 
When removing `include` from common, the result is expected.

**Comment by bebraw** [comment]
Can you PR a fix? Thanks.

**Comment by andrewMuntyan** [comment]
Hi, i see bunch of tests which tell me that this is normal behavior
```
11) should not merge to parent if there is no include for loaders #68
12) should not merge to parent if there is no exclude for loaders #68 
```

Should we add some explanation about this to `README.MD`?

**Comment by bebraw** [comment]
@andrewMuntyan Yup, please PR.

**Comment by bebraw** [comment]
Changing the behavior would be a breaking change but we could possibly do that as well. Just a new major version.

**Comment by chinesedfan** [comment]
@bebraw Personally, I like the current implementation. And #122 should have list all current related rule fields.

**Comment by bebraw** [comment]
I'll drop support for `merge.smart` and `merge.smartStrategy` in the next major version as it's tricky to support due to different webpack versions and overall complexity.

Can you rewrite the configuration in terms of regular `merge` or `mergeStrategy`? I use solely `merge` for all of my personal work as it's predictable.
